import { Footer, PageHeader } from "../components";

export const metadata = { title: "Technology | Orvessian", description: "Private evidence, explicit checks and independent anchoring for autonomous work.", openGraph: { images: [] }, twitter: { images: [] } };

const checks = [["Evidence integrity", "Disclosed bytes match their commitment. This does not establish whether the evidence is true."], ["Issuer signature", "A particular key signed a record. Identity and trust in that issuer require additional checks."], ["Authority", "The relevant permission holds at a defined reference point. Runtime enforcement remains a separate responsibility."], ["Policy proof", "A precisely defined computation evaluated a committed action against a committed policy. Not a general proof of AI correctness."], ["Human review", "A reviewer attests to a specific decision and evidence version. Human judgement remains fallible."], ["Chain inclusion", "A record belongs to a checked chain view or batch. Inclusion does not authorise every leaf or guarantee permanent finality."]];

export default function Technical() {
  return <main><PageHeader label="Technology / boundaries made visible" title="Private evidence. Explicit checks. A shared anchor."><p>Orvessian connects records across systems without pretending that every kind of trust is the same.</p></PageHeader>
    <section className="architecture"><p className="eyebrow">The architecture</p><h2>Keep the boundaries <em>visible.</em></h2><div className="system-map">{[["01", "Application", "Your agent or runtime executes the work and enforces permissions."], ["02", "Organisation", "Authority and sensitive evidence remain within the organisation's controls."], ["03", "Receipt", "Signed records bind events to evidence; verifiers check specific properties."], ["04", "Shared anchor", "Base records batch commitments; private records, indexes and inclusion proofs support review."]].map(([number, title, copy]) => <div className="map-node" key={number}><b>{number}</b><h3>{title}</h3><p>{copy}</p></div>)}</div><p className="caption">Architecture direction. Components have different readiness levels; the complete product is not a production release.</p></section>
    <section className="foundation-content"><p className="eyebrow">What does “verified” actually mean?</p><h2>Six checks. Six different answers.</h2><div className="assurance-grid">{checks.map(([title, copy]) => <article key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section className="foundation-content safety-product"><p className="eyebrow">Safety evidence boundary</p><h2>Chain confirmation is evidence, not containment.</h2><p>A policy gateway, sandbox or security monitor must make a local allow, block, pause or revoke decision without waiting for a ledger. Orvessian can then bind selected policy versions, alerts and authorised interventions into an independently checkable timeline.</p><div className="notice"><strong>Distributed does not mean AI-resistant</strong><p>A confirmed record may be harder for one operator to silently change than a private database entry. Attackers can still compromise keys, source events, runtimes, relayers, indexes, contracts or consensus. The claim must always be checked against the actual system and its operators.</p></div><a className="arrow-link" href="/safety">Explore the safety-evidence model <span>→</span></a></section>
    <section className="technical-baseline"><div><p className="eyebrow">Current technical baseline</p><h2>Build the layers. Publish their limits.</h2></div><div className="baseline-grid"><article><span>01 / receipt</span><h3>General format 0.4.0-alpha</h3><p>Versioned profiles, exact-byte commitments, signatures, private openings, streams and batch links exist in local reference tooling.</p></article><article><span>02 / proof</span><h3>A narrow deterministic statement</h3><p>The internal alpha’s RISC Zero policy path proves a committed action against committed policy and configuration. It does not prove AI execution or outcome truth.</p></article><article><span>03 / foundation</span><h3>Base Sepolia pilot</h3><p>A supervised relayer sponsors synthetic batch transactions on Base Sepolia. The portal checks canonical inclusion; production mainnet operations remain gated.</p></article></div></section>
    <section className="foundation-band"><div><p className="eyebrow">Independent infrastructure</p><h2>Why anchor on Base?</h2></div><div><p>Base is the accepted launch settlement direction. Orvessian operates a governance and verification application on that network; it is not launching its own L1 or a separate L2.</p><p>Private structured records and receipt openings stay in the platform database. Only batch commitments are published. The recording key and gas-paying publisher have distinct roles; customers need neither ETH nor a native token.</p><p>Current evidence comes from Base Sepolia, including sponsored submission and restart recovery. Historical mining experiments are outside the launch plan. Larger and hierarchical batches still need measurement.</p></div></section>
    <section className="foundation-content narrow"><h2>Prove the specific claim.</h2><p>General 0.4.0-alpha receipts and the authorised AVR flow have different capabilities. Missing evidence, unsupported checks and unknown authority should remain visible rather than becoming a universal success badge.</p><div className="actions"><a className="button primary" href="/developers">Explore the developer path →</a><a className="arrow-link" href="/whitepaper">Read the working technical paper</a></div></section><Footer /></main>;
}
