import Link from "next/link";
import { Footer, PageHeader } from "../components";
export const metadata = { title: "Technology | Orvessian", description: "Private evidence, explicit checks and independent anchoring for autonomous work.", openGraph: { images: [] }, twitter: { images: [] } };
const checks = [["Evidence integrity","Disclosed bytes match their commitment. This does not establish whether the evidence is true."],["Issuer signature","A particular key signed a record. Identity and trust in that issuer require additional checks."],["Authority","The relevant permission holds at a defined reference point. Runtime enforcement remains a separate responsibility."],["Policy proof","A precisely defined computation evaluated a committed action against a committed policy. Not a general proof of AI correctness."],["Human review","A reviewer attests to a specific decision and evidence version. Human judgement remains fallible."],["Chain inclusion","A record belongs to a checked chain view or batch. Inclusion does not authorise every leaf or guarantee permanent PoW finality."]];
export default function Technical() { return <main><PageHeader label="Technology" title="Private evidence. Explicit checks. A shared anchor."><p>The verification layer connects records across systems without pretending that every kind of trust is the same.</p></PageHeader>
<section className="architecture"><p className="eyebrow">The architecture</p><h2>Keep the boundaries <em>visible.</em></h2><div className="system-map">{[["01","Application","Your agent or runtime executes the work and enforces permissions."],["02","Organisation","Authority and sensitive evidence remain within the organisation's controls."],["03","Receipt","Signed records bind events to evidence; verifiers check specific properties."],["04","Shared anchor","The L1 records commitments; indexes and inclusion proofs support lookup."]].map(([number,title,copy]) => <div className="map-node" key={number}><b>{number}</b><h3>{title}</h3><p>{copy}</p></div>)}</div><p className="caption">Architecture direction. Components have different readiness levels; the complete product is not a production release.</p></section>
<section className="foundation-content"><p className="eyebrow">What does “verified” actually mean?</p><h2>Six checks. Six different answers.</h2><div className="assurance-grid">{checks.map(([title,copy]) => <article key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
<section className="foundation-band"><div><p className="eyebrow">Independent infrastructure</p><h2>Why build an L1?</h2></div><div><p>The project is developing an independent EVM-compatible Proof-of-Work L1 as a shared verification and anchoring foundation. The goal is a common record that is not confined to one application provider.</p><p>A new chain also brings security bootstrapping, operator and ecosystem costs. Existing-chain anchoring and conventional transparency services are meaningful alternatives—not problems that a new token automatically solves.</p><p>The integrated alpha uses a custom-genesis Ethash development chain. It does not establish final consensus parameters or production capacity.</p></div></section>
<section className="foundation-content narrow"><h2>Prove the specific claim.</h2><p>The alpha's policy-proof work checks deterministic evaluation of a committed action against a committed policy/configuration. It does not establish that a particular AI model ran, that its answer is true, or that a physical action was safe.</p><p>General 0.4.0-alpha receipts and the authorised AVR flow have different capabilities. Missing evidence, unsupported checks and unknown authority should remain visible rather than becoming a universal success badge.</p><div className="actions"><Link className="button primary" href="/developers">Explore the developer path →</Link><Link className="arrow-link" href="/status">Read the development status</Link></div></section><Footer/></main>; }
