import { Footer, Nav } from "../components";

export const metadata = { title: "Our vision | Orvessian", description: "A world that can delegate to autonomous systems and still govern and account for the outcome.", openGraph: { images: [] }, twitter: { images: [] } };

export default function Vision() {
  return <main>
    <section className="vision-hero"><Nav dark/><div className="vision-hero-copy" id="content"><p className="eyebrow">Our vision</p><h1>More freedom to act.<br/><em>More reason to trust.</em></h1><p>We want people to delegate ambitious work to autonomous systems—and still govern and account for the decisions made in their name.</p></div><p className="image-caption">Conceptual image · people remain central to the story</p></section>
    <section className="foundation-content narrow vision-manifesto"><p className="eyebrow">Why this deserves to exist</p><h2>Delegation should not end the conversation.</h2><p>A useful agent can take a brief and carry it across many tools. But the person responsible for the outcome still needs a way to ask: what happened, why was it allowed, and what did someone actually check?</p><p>That history should not disappear when a session ends, a provider changes or work crosses an organisational boundary.</p><p>Orvessian is building a verification foundation for that history: portable records, evidence people can inspect, and a clear distinction between a claim and a check.</p><a className="arrow-link" href="/in-action">See the idea in one job →</a></section>
    <section className="foundation-band"><div><p className="eyebrow">Autonomy, governed</p><h2>Not a person at every step.<br/>A person with a meaningful role.</h2></div><div><p>People set the brief, define acceptable risk and make the judgements that should not be silently delegated. Agents handle routine work within the controls of their application.</p><p>When something changes, the decision should be visible. When someone says no, that decision should remain part of the record.</p><p>The goal is not certainty. It is a stronger basis for trust: clear authority, clear controls and a history people can inspect.</p></div></section>
    <section className="foundation-content"><p className="eyebrow">Start with a real need. Earn the right to expand.</p><h2>One foundation.<br/>A wider horizon.</h2><div className="horizon-list">
      <article><span>01 / First focus</span><div><h3>Enterprise agent workflows</h3><p>Begin where evidence and review already matter: a recommendation, an exception, a decision and a record that another team can inspect.</p><p className="horizon-gate">The next proof: independent integrations and useful pilot results.</p></div></article>
      <article><span>02 / Expansion direction</span><div><h3>Work across organisations</h3><p>Help counterparties inspect the authority, deliverables and acceptance behind agent services. Payments and disputes need their own verified rules.</p><p className="horizon-gate">The next proof: settlement, counterparty and dispute handling in real workflows.</p></div></article>
      <article><span>03 / Longer-term ambition</span><div><h3>Machines in the physical world</h3><p>Extend the record to inspections, equipment and other machine events. A digital history is useful only when its capture and interpretation deserve trust.</p><p className="horizon-gate">The next proof: device identity, capture integrations and domain-specific assurance.</p></div></article>
    </div></section>
    <section className="robotics"><div className="robot-image" role="img" aria-label="Conceptual image of a technician reviewing work near a robot"/><div><p className="eyebrow">Physical autonomy / future direction</p><h2>A record supports accountability.<br/>It does not replace safety.</h2><p>A machine-event receipt is not a safety certificate. Sensors, operators and reviewers need their own assurance. Real-time control and emergency stops belong outside the blockchain.</p><a className="button primary" href="/technology">Explore the design →</a></div></section>
    <section className="foundation-content narrow"><h2>Big ambition.<br/>Specific next steps.</h2><p>The receipt tooling is in local alpha. Broader review experiences, independent trials and production readiness are still ahead. We want the project to earn confidence through inspectable progress.</p><div className="actions"><a className="button primary" href="/status">See where we are →</a><a className="arrow-link" href="/whitepaper">Explore the research</a></div></section><Footer/>
  </main>;
}
