const assert = require('node:assert/strict'); const fs = require('node:fs'); const os = require('node:os'); const path = require('node:path'); const test = require('node:test');
const { createSyntheticIngressHttpServer } = require('./synthetic-ingress-http'); const { SyntheticIngressService } = require('./synthetic-ingress-service'); const { BaseSepoliaSyntheticBatchAdapter } = require('../../sdk/typescript/base-sepolia-batch-adapter'); const { createPresentation } = require('../../sdk/typescript/avr-presentation'); const receipt = require('../../fixtures/avr/receipt-v0.1.0-draft.json');
const key = 'http-development-key-1234';
function presentation() { const copy = structuredClone(receipt); copy.commitments.input = `0x${'77'.repeat(32)}`; return createPresentation(copy, { level: 'commitment-only' }); }
test('serves health and only admits authenticated synthetic submissions', async () => {
 const ingress = new SyntheticIngressService({ apiKey:key, stateFile:path.join(fs.mkdtempSync(path.join(os.tmpdir(),'aichain-http-')),'state.json'), adapter:new BaseSepoliaSyntheticBatchAdapter({contract:'0x5781540E4682A9D35011C94A25F615e438E8E7aF',publisher:'0xec502b5f4D1925138a7409D9a7b55Fba20e13cc3'}) }); const events=[]; const server=createSyntheticIngressHttpServer({ingress,logger:e=>events.push(e)}); await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve)); const base=`http://127.0.0.1:${server.address().port}`;
 try { assert.equal((await fetch(`${base}/health`)).status,200); let response=await fetch(`${base}/v1/synthetic/receipts`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({synthetic:true,presentation:presentation()})}); assert.equal(response.status,401); response=await fetch(`${base}/v1/synthetic/receipts`,{method:'POST',headers:{'content-type':'application/json','x-aichain-api-key':key},body:JSON.stringify({synthetic:false,presentation:presentation()})}); assert.equal(response.status,400); response=await fetch(`${base}/v1/synthetic/receipts`,{method:'POST',headers:{'content-type':'application/json','x-aichain-api-key':key},body:JSON.stringify({synthetic:true,presentation:presentation()})}); assert.equal(response.status,202); assert.equal(events.at(-1).receiptId.length,66); } finally { await new Promise(resolve=>server.close(resolve)); }
});

test('prepares a two-receipt Base batch through the HTTP boundary without broadcasting', async () => {
 const stateFile=path.join(fs.mkdtempSync(path.join(os.tmpdir(),'aichain-http-e2e-')),'state.json'); const adapter=new BaseSepoliaSyntheticBatchAdapter({contract:'0x5781540E4682A9D35011C94A25F615e438E8E7aF',publisher:'0xec502b5f4D1925138a7409D9a7b55Fba20e13cc3'}); const ingress=new SyntheticIngressService({apiKey:key,stateFile,adapter,queuePolicy:{maxBatchReceipts:2,microBatchMs:100}}); const server=createSyntheticIngressHttpServer({ingress}); await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve)); const base=`http://127.0.0.1:${server.address().port}`; const submit=async value=>fetch(`${base}/v1/synthetic/receipts`,{method:'POST',headers:{'content-type':'application/json','x-aichain-api-key':key},body:JSON.stringify({synthetic:true,presentation:value})});
 try { assert.equal((await submit(presentation())).status,202); const second=structuredClone(presentation()); second.receipt.commitments.input=`0x${'88'.repeat(32)}`; const { createPresentation }=require('../../sdk/typescript/avr-presentation'); assert.equal((await submit(createPresentation(second.receipt,{level:'commitment-only'}))).status,202); const response=await fetch(`${base}/v1/synthetic/batches/prepare`,{method:'POST',headers:{'content-type':'application/json','x-aichain-api-key':key},body:JSON.stringify({force:true})}); const prepared=await response.json(); assert.equal(response.status,200); assert.equal(prepared.status,'prepared-for-metamask'); assert.equal(prepared.receiptIds.length,2); assert.equal(prepared.transaction.to.toLowerCase(),adapter.contract.toLowerCase()); assert.equal(JSON.parse(fs.readFileSync(stateFile)).records.every(record=>record.status==='queued-for-anchor'),true); } finally { await new Promise(resolve=>server.close(resolve)); }
});
