import { Footer, Nav } from "./components";
import { LivingReceipt } from "./living-receipt";
const pillars = [
  ["01","Know the authority","Connect a recorded action to the organisation and permissions behind it."],
  ["02","Keep the evidence","Bind a record to the evidence used, without publishing the private work itself."],
  ["03","See what was checked","Distinguish a signature, an evidence check and a human decision. Each answers a different question."],
];
export default function Home() {
  return <main>
    <section className="cinematic-hero"><Nav dark/><div className="cinematic-layout"><div className="cinematic-copy" id="content"><p className="eyebrow">The verification layer for autonomous work</p><h1>Autonomous <br/>agents.<br/><em>Human certainty.</em></h1><p className="cinematic-lede">Give autonomous work a record people can inspect. What was authorised. What happened. What was checked.</p><div className="actions"><a className="button primary" href="/in-action#walkthrough">See it in action <span>→</span></a><a className="button cinematic-secondary" href="/developers">Build with receipts <span>→</span></a></div><p className="hero-readiness">Receipt tooling in alpha. Broader product in development.</p></div><LivingReceipt/></div><div className="hero-bottom-line"><span>AUTONOMY WITH AN ACCOUNTABLE HISTORY</span><a href="#why-it-matters">The idea behind the record ↓</a></div></section>
    <section className="intro" id="why-it-matters"><p className="eyebrow">The work is autonomous. The accountability still matters.</p><h2>Delegating the work should not mean <em>losing the story.</em></h2><p className="section-copy">When an agent moves between tools and teams, someone still needs to explain the outcome. What was it allowed to do? Which evidence did it use? Who reviewed the exception? Those answers should not be scattered across a dozen systems.</p></section>
    <section className="receipt-section"><div className="receipt-copy"><p className="eyebrow">A record people can inspect</p><h2>Give the work a <em>receipt.</em></h2><p>A verification receipt connects a recorded event to signed assertions and evidence. Private information stays with its custodian; authorised reviewers can inspect what they need.</p><a className="arrow-link" href="/product">Explore the product <span>→</span></a></div>
      <div className="receipt"><div className="receipt-head"><span>ORVESSIAN / WORK RECORD</span><span className="pill">ILLUSTRATIVE</span></div><div className="receipt-job"><span className="job-icon">◒</span><div><small>SUPPLIER ASSESSMENT</small><strong>A recommendation, with its history.</strong></div></div><div className="receipt-row"><span>Evidence</span><strong>Version recorded</strong></div><div className="receipt-row"><span>Exception</span><strong>Document expired</strong></div><div className="receipt-row"><span>Human decision</span><strong>Request an update</strong></div><div className="receipt-footer">A record of a decision—not a guarantee of correctness.</div></div>
    </section>
    <section className="principles"><div><p className="eyebrow">Three questions. Explicit answers.</p><h2>More clarity behind <em>every check.</em></h2></div><div>{pillars.map(([num,title,text]) => <article className="check" key={num}><span>{num}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>
    <section className="foundation-band"><div><p className="eyebrow">From ambition to evidence</p><h2>A working alpha.<br/>An honest boundary.</h2><p>Local receipt tooling and a bounded integration demonstrate parts of the foundation. Stable releases, independent trials and production readiness are still ahead.</p></div><div className="foundation-links"><a href="/developers">Try the local receipt example <span>01</span></a><a href="/technology">Understand the architecture <span>02</span></a><a href="/status">Inspect the current status <span>03</span></a></div></section>
    <section className="story" id="story"><p className="eyebrow">Our vision</p><h2>A world that can delegate—and still <em>account for the outcome.</em></h2><p>We begin with enterprise agent workflows where evidence and review already matter. The longer-term ambition reaches beyond software to machines acting in the physical world.</p><p>Human certainty is the ambition. In practice, every check has a scope: a signature is not proof of truth, and a recorded review is not an infallible decision.</p><div className="actions"><a className="button primary" href="/vision">Explore the vision <span>→</span></a><a className="arrow-link" href="/in-action">Bring the idea to life</a></div></section><Footer/>
  </main>;
}
