import { Footer, Nav } from "./components";
import { AgentGovernanceStory } from "./agent-governance-story";
import { PlatformPreview } from "./platform-preview";
const capabilities=[
 ["01 / ACTIVITY","See the work taking place.","Explore reporting agents, recorded decisions and activity over time. Filter the view by project and model deployment."],
 ["02 / OUTCOMES","Make performance understandable.","Compare labelled outcomes across model cohorts. See sample sizes and missing labels alongside the results."],
 ["03 / INVESTIGATION","Get from a trend to a decision.","Investigate submitted incidents and the structured context behind individual decisions. Bring the relevant evidence into the review."]
];
export default function Home(){return <main className="platform-site">
 <section className="platform-hero"><Nav dark/><div className="platform-hero-grid" id="content"><div><p className="eyebrow">Governance for AI agents</p><h1>Understand your agents.<br/><em>Account for their decisions.</em></h1><p className="platform-lede">See what your AI agents are doing, measure recorded outcomes and investigate the decisions that matter. Bring governance reporting and independently verifiable evidence into one workspace.</p><div className="actions"><a className="button primary" href="/portal">Explore the governance demo ↗</a><a className="platform-secondary" href="/product">Discover the platform →</a></div><p className="platform-readiness">Synthetic demo · Private testnet pilot · Production access in development</p></div><PlatformPreview/></div><div className="platform-promise"><span>Activity you can understand</span><span>Decisions you can investigate</span><span>Evidence you can independently check</span></div></section>
 <section className="platform-section"><div className="platform-section-heading"><p className="eyebrow">The questions behind responsible AI</p><h2>What are your agents doing?<br/>How well is it working?</h2><p>Give engineering, operations and governance teams a shared view of recorded AI activity, from the daily overview to the detail of an individual decision.</p></div><div className="platform-cards">{capabilities.map(([label,title,copy])=><article key={label}><p className="eyebrow">{label}</p><h3>{title}</h3><p>{copy}</p><a href="/product">Explore this workflow →</a></article>)}</div></section>
 <AgentGovernanceStory/><section className="platform-evidence"><div><p className="eyebrow">Our evidence foundation</p><h2>Governance reporting.<br/><em>Cryptographic accountability.</em></h2><p>Signed records and cryptographic hashes anchored to the Base blockchain give authorised reviewers an independent reference for checking the evidence.</p><p>A change to an anchored record can be detected by checking it against its original commitment. Export the record and proof to verify the checks outside the portal.</p><a className="button primary" href="/technology">Explore the verification layer →</a></div><div className="evidence-steps">{[["01","Structured record","Selected context stays private; source conversations remain in your systems."],["02","Signature & proof","A recording-service signature and batch membership proof connect the record to its commitment."],["03","Blockchain anchor","A cryptographic batch commitment is published on Base. The pilot uses Base Sepolia."],["04","Independent check","Check the record, signature, proof and canonical anchor with an authorised evidence export."]].map(([n,title,copy])=><div key={n}><span>{n}</span><div><h3>{title}</h3><p>{copy}</p></div></div>)}<p className="evidence-boundary">Tamper-evident records do not prove complete capture, source truth or AI correctness. Private storage and access controls remain essential.</p></div></section>
 <section className="platform-section platform-workflow"><div><p className="eyebrow">Built around the review</p><h2>From “what changed?”<br/>to a record you can inspect.</h2><p>Start with the overview. Compare outcomes. Open a decision. Follow its evidence. Keep the business question and verification in the same workflow.</p><a className="arrow-link" href="/portal">Try the synthetic workspace →</a></div><div className="workflow-example"><p className="eyebrow">Illustrative purchasing workflow</p><h3>A decision needs a closer look.</h3><ol><li><strong>Find the activity</strong><span>A purchasing agent records a request above its policy limit.</span></li><li><strong>Inspect the context</strong><span>Review the submitted policy reference and approval outcome.</span></li><li><strong>Check the evidence</strong><span>Inspect the signature, proof and anchor state in the pilot workspace.</span></li></ol></div></section>
 <section className="platform-section platform-next"><div><p className="eyebrow">A platform with a clear direction</p><h2>Visibility today.<br/>Deeper governance next.</h2></div><div><p>The synthetic platform demonstrates activity reporting, model comparisons, submitted incidents and evidence investigation. Agent heartbeats, configurable alerts, incident ownership and scheduled reports are on the roadmap.</p><p>Submit selected structured data through the API. Your source conversations, documents and media stay in your systems.</p><div className="actions"><a className="button primary" href="/products/governance-preview">Explore proposed plans →</a><a className="arrow-link" href="/status">View readiness</a></div></div></section><Footer/></main>;}
