"use client";
import { useState } from "react";
const views = {
 Activity: {label:"Recorded decisions",value:"1,280",detail:"12 reporting agents · illustrative 7-day window",bars:[35,48,42,65,57,81,94]},
 Outcomes: {label:"Reviewed decisions",value:"960 / 1,280",detail:"75% review coverage · 320 awaiting a label",bars:[28,35,45,41,61,70,75]},
 Evidence: {label:"Decision PO-1042",value:"Inspect the evidence",detail:"Illustrative checks · no live verification performed here",bars:[]}
};
export function PlatformPreview(){
 const [selected,setSelected]=useState<keyof typeof views>("Activity");const view=views[selected];
 return <div className="platform-preview"><div className="preview-top"><span>◒ ORVESSIAN / GOVERNANCE WORKSPACE</span><span className="preview-demo">Illustrative data</span></div><div className="preview-tabs" aria-label="Preview views">{Object.keys(views).map(key=><button type="button" key={key} aria-pressed={selected===key} onClick={()=>setSelected(key as keyof typeof views)}>{key}</button>)}</div><div className="preview-content" aria-live="polite"><div className="preview-summary"><div className="preview-kpi"><span>{view.label}</span><strong>{view.value}</strong><small>{view.detail}</small></div>{selected!=="Evidence"?<div className="preview-chart" aria-hidden="true">{view.bars.map((height,i)=><div key={i}><span style={{height:height+"%"}}/><small>{["M","T","W","T","F","S","S"][i]}</small></div>)}</div>:<ol className="preview-proof"><li>Record integrity <span>Example: matches</span></li><li>Recorder signature <span>Example: valid</span></li><li>Batch membership <span>Example: valid</span></li><li>Base anchor <span>Example: confirmed</span></li></ol>}</div>
 {selected!=="Evidence"?<div className="preview-table-wrap"><table className="preview-table"><caption>{selected==="Activity"?"Reporting activity by agent":"Reviewed outcomes by agent"} · synthetic example</caption><thead><tr><th scope="col">Agent / deployment</th><th scope="col">Decisions</th><th scope="col">{selected==="Activity"?"Latest reported action":"Reviewed / total"}</th></tr></thead><tbody><tr><th scope="row">Purchasing assistant <small>procurement-v2</small></th><td>480</td><td>{selected==="Activity"?"Approval requested":"360 / 480"}</td></tr><tr><th scope="row">Support triage <small>support-v3</small></th><td>640</td><td>{selected==="Activity"?"Case routed":"480 / 640"}</td></tr><tr><th scope="row">10 other reporting agents</th><td>160</td><td>{selected==="Activity"?"Decision recorded":"120 / 160"}</td></tr></tbody></table></div>:<p className="preview-proof-note">Each check answers a different question. A valid anchor does not establish source truth or AI correctness.</p>}
 <details className="preview-record"><summary>Investigate purchasing decision PO-1042 <span>+</span></summary><div><dl><div><dt>Recorded action</dt><dd>Approval requested</dd></div><div><dt>Submitted policy context</dt><dd>Requested spend above the configured limit</dd></div><div><dt>Reported outcome</dt><dd>Human review pending</dd></div></dl><p>This example shows submitted context, not an independently detected policy breach. The customer's application enforces the limit.</p></div></details></div><a className="preview-bottom" href="/portal">Open the interactive synthetic demo <span>↗</span></a></div>;
}
