export const storySlides = [
  { id: "brief", label: "The brief", role: "Operations lead", title: "Delegate the research.\nKeep the final say.", text: "An agent is asked to assess a supplier using approved sources. It may gather evidence and make a recommendation. It may not place an order.", document: "Work mandate", status: "Scope defined", fields: [["Job", "Prepare supplier recommendation"], ["Sources", "Approved documents only"], ["Boundary", "No purchase authority"]], note: "The application enforces the brief. A receipt does not enforce it by itself." },
  { id: "evidence", label: "The evidence", role: "Research agent", title: "Useful work.\nAn inspectable trail.", text: "The agent gathers the documents, runs the agreed checks and drafts its recommendation. The versions behind its work are retained for review.", document: "Evidence collection", status: "Material gathered", fields: [["Supplier profile", "Source version retained"], ["Insurance certificate", "Version 1 recorded"], ["Recommendation", "Draft ready for review"]], note: "Recorded evidence is not automatically truthful evidence." },
  { id: "exception", label: "The exception", role: "Workflow rule", title: "One expired document.\nA reason to pause.", text: "The required insurance certificate has expired. The work can be recorded, but acceptance is held. An authorised person needs to make the next call.", document: "Review checkpoint", status: "Acceptance on hold", fields: [["Required document", "Insurance certificate"], ["Checklist result", "Expired"], ["Next step", "Human review required"]], note: "This is a proposed workflow. It is not a live approval system." },
  { id: "review", label: "The decision", role: "Authorised reviewer", title: "A human decision.\nNot an automatic yes.", text: "A reviewer sees the exception and the evidence behind it. Explore three alternative endings; each leaves a different record.", document: "Decision record", status: "Choose a story path", fields: [["Review basis", "Organisation's criteria"], ["Material", "Exact version disclosed"], ["Authority", "Recommendation only"]], note: "Scenario choices below illustrate outcomes. They do not approve or reject real work." },
  { id: "receipt", label: "The receipt", role: "Recorded outcome", title: "Keep the decision.\nKeep its history.", text: "The result connects to the brief, evidence and review history. A recipient can ask which version was considered and what the reviewer actually decided.", document: "Work receipt", status: "Illustrative record", fields: [["Job", "Supplier recommendation"], ["Earlier exception", "Certificate expired"], ["Purchase permission", "Not granted by this review"]], note: "No signature or anchor check is executed by this illustration." },
  { id: "check", label: "The later check", role: "Independent reviewer", title: "The file changed.\nThe old decision did not.", text: "If a disclosed file does not match the recorded commitment, the integrity check fails. A genuine update needs a new record and a fresh decision—not silent replacement.", document: "Evidence comparison", status: "Mismatch: review needed", fields: [["Recorded version", "Exact version retained"], ["Disclosed file", "Different bytes"], ["Result", "Does not match the record"]], note: "Missing evidence stays unavailable. A matching file still needs a separate truth appraisal." },
];

export const storyPaths = [
  { id: "accepted", label: "Accepted", title: "Better evidence. A fresh decision.", text: "An updated certificate arrives. The reviewer assesses version 2 and accepts the recommendation. The original exception stays in the history.", status: "Recommendation accepted", evidence: "Updated certificate · version 2", limit: "No order placed. Supplier safety is not guaranteed." },
  { id: "more-evidence", label: "More evidence", title: "Not yet is a useful answer.", text: "The reviewer requests an updated certificate. Acceptance remains on hold. If the deadline passes, silence does not turn into permission.", status: "Further evidence requested", evidence: "Expired certificate · version 1", limit: "No acceptance while review is unresolved." },
  { id: "rejected", label: "Rejected", title: "A clear reason not to proceed.", text: "The evidence does not meet the organisation's criteria. The reviewer rejects the recommendation and records why. Reassessment would be a new, linked decision.", status: "Recommendation rejected", evidence: "Evidence assessed against criteria", limit: "The rejection remains in the history." },
];
