import { Footer, PageHeader, repository } from "../components";

export const metadata = {
  title: "Technical paper | Orvessian",
  description: "A working technical paper on verification receipts for autonomous systems, grounded in the current alpha source baseline.",
  openGraph: { images: [] },
  twitter: { images: [] },
};

const claims = [
  ["A receipt", "Binds declared event and evidence metadata into a versioned record."],
  ["A signature", "Shows that a particular key signed that record. It does not establish trust in the key holder."],
  ["An anchor", "Makes a receipt or batch inclusion checkable against a chain view. It does not recover lost evidence."],
  ["A proof", "Can establish a narrowly defined computation. It is not a general proof that an AI result is true."],
];

const sections = [
  ["01", "The problem", "Autonomous work is useful precisely because it crosses systems without asking a person to inspect every step. But when a consequential result needs review, the relevant history is often scattered across application logs, private documents, access systems and hand-offs. Orvessian is exploring a portable verification receipt that lets a reviewer ask narrower, useful questions: what was recorded, which bytes were considered, who signed, which permission applied, and whether an anchor can be checked."],
  ["02", "A record, not a verdict", "The central design rule is to keep assurance dimensions separate. A matching commitment supports evidence integrity. A recovered signature supports a statement by a key. An authority check has its own reference point. A policy proof has its own statement. Human appraisal remains a human judgement. The system should be able to return unknown, unsupported, expired or unavailable instead of flattening them into a green badge."],
  ["03", "The receipt contract", "The implemented general format is 0.4.0-alpha. It carries a pinned profile, chain and anchor destination, issuer and subject identifiers, an event, one to thirty-two evidence commitments and optional links. Machine profiles can also carry clock, uncertainty, session and sequence information. Exact evidence bytes are committed outside the chain; salts, evidence locations and private material stay with the appropriate custodian."],
  ["04", "Profiles make context explicit", "A receipt envelope deliberately does not decide what a supplier file, an agent run or a machine event means. Profiles define the evidence roles and assurance language. The current source includes agent, robotics, commerce, content, supply-chain and generic profiles. The agent profile binds inputs, outputs, configuration and policy context; it does not prove inference correctness, authorisation or complete tool-call history. The robotics profile is an audit trail, not a real-time safety controller."],
  ["05", "Anchoring and verification", "A receipt may be individually anchored, or included in a retained batch manifest whose root is anchored. Verification checks must be performed separately: profile and definition bytes, evidence opening, signature, destination, canonical transaction and block, emitted anchor event, and individual or batch membership. A batch submitter is not automatically the receipt signer; a matching hash does not establish the semantics of the underlying evidence."],
  ["06", "The proof boundary", "The alpha ZK-001 path uses RISC Zero to prove deterministic evaluation of a committed action against a committed policy and configuration. The integrated internal alpha recorded a real proof, a pinned verifier path, a bounded ingress and batch flow, durable index recovery and lookup. That evidence does not establish AI execution, model-output truth, real-world outcomes or production security. General verification receipts do not automatically inherit authorised AVR or ZK-001 semantics."],
  ["07", "Base settlement and the governance platform", "Base is the accepted launch direction, with live synthetic batches on Base Sepolia. Orvessian runs an application on Base, not its own L1 or separate L2. A private database holds bounded structured governance records and evidence openings; a separate gas wallet publishes commitments. The authenticated portal connects reporting and investigations to signed receipts and checked anchors. Historical consensus and mining experiments are outside the launch critical path."],
  ["08", "What has to be true next", "The supervised synthetic worker and private API have passed bounded recovery checks; a 24-hour reliability run is in progress. Release work includes measured capacity, independent developer trials, stable SDK packaging, source authentication, production identity, storage and key operations, environment separation, encrypted backups and commercial readiness. Configurable governance rules and alert delivery remain future product increments. Testnet confirmations are not production assurance or Ethereum finality."],
];

export default function Whitepaper() {
  return <main>
    <PageHeader label="Technical paper / working edition · 27 September 2026" title="A shared history for autonomous work.">
      <p>Verification Receipts for accountable agents and machines. This living paper reflects the repository’s current alpha baseline; it is neither a final protocol specification nor a production-readiness claim.</p>
    </PageHeader>
    <section className="paper-intro" id="content">
      <div><p className="eyebrow">The proposition</p><h2>Autonomy needs a history people can <em>interrogate.</em></h2></div>
      <div><p>Orvessian is building toward a verification layer that lets applications retain private working material while making specific records and checks inspectable. The point is not to declare an outcome universally verified. The point is to preserve the basis for a better question.</p><a className="arrow-link" href={`${repository}/blob/main/docs/verification-receipt-readiness-review.md`}>Read the current readiness review <span>→</span></a></div>
    </section>
    <section className="claim-spectrum"><div className="paper-section-head"><p className="eyebrow">Four distinct claims</p><h2>One receipt can support several checks. They are not interchangeable.</h2></div><div className="claim-grid">{claims.map(([title,copy], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    <section className="paper-body">{sections.map(([number,title,copy]) => <article key={number}><div><span>{number}</span><h2>{title}</h2></div><p>{copy}</p></article>)}</section>
    <section className="paper-evidence"><p className="eyebrow">Current source baseline</p><h2>Implemented alpha, bounded evidence, open release gates.</h2><div className="evidence-columns"><article><h3>Implemented in local reference tooling</h3><p>General 0.4.0-alpha receipts, typed profiles, canonical commitments, signed presentations, private evidence openings, stream links, batch manifests and reference TypeScript/Python tooling.</p></article><article><h3>Integrated evidence and testnet pilot</h3><p>Earlier internal proof experiments retain their scope. The current governance pilot adds private structured records, signed receipts, sponsored Base Sepolia batches and live portal verification.</p></article><article><h3>Still not claimed</h3><p>Production readiness, public customer onboarding, completed independent security review, live machine safety assurance, universal AI correctness or a stable published SDK.</p></article></div><div className="actions"><a className="button primary" href="/developers">Run the local receipt example →</a><a className="arrow-link" href="/technology">See the architecture and boundaries</a></div></section>
    <section className="paper-sources"><p className="eyebrow">Primary material</p><h2>Trace the paper back to the work.</h2><a href={`${repository}/blob/main/docs/verification-receipt-developer-guide.md`}>General verification-receipt developer guide <span>0.4.0-alpha format →</span></a><a href={`${repository}/blob/main/docs/archive/2026-09-27/completed-stages/phase-3-integrated-alpha.md`}>Integrated internal alpha <span>Reproduction and limits →</span></a><a href={`${repository}/blob/main/docs/archive/2026-09-27/own-chain/phase-4-closed-testnet-foundation.md`}>Historical own-chain foundation <span>Superseded launch direction →</span></a><a href={`${repository}/blob/main/docs/archive/2026-09-27/own-chain/phase-4-acceptance-and-monitoring-policy.md`}>Acceptance and monitoring policy <span>Thresholds and interpretation →</span></a></section>
    <Footer />
  </main>;
}
