const test=require('node:test'),assert=require('node:assert/strict');
const {Wallet,keccak256}=require('ethers');
const {GovernanceStore}=require('./store');
const {prepareBatch,attachTransaction,inspectEvidence,CONTRACT}=require('./evidence.cjs');
const {AVR_EVENTS}=require('../../sdk/typescript/avr-anchor-verifier');
const fixture=require('../../fixtures/governance/paired-model-comparison-v0.1.0-draft.json');
const p={tenant:'org-demo',project:'claims-governance-demo'},publisher='0x'+'aa'.repeat(20),tx='0x'+'bb'.repeat(32),blockHash='0x'+'cc'.repeat(32);
async function setup(){const store=new GovernanceStore(':memory:');for(const e of fixture.events.slice(0,3))store.ingest(e,p);const signer=Wallet.createRandom();const batch=await prepareBatch(store,p,signer,{publisher});const event=store.get(p,fixture.events[0].eventId);return {store,signer,batch,event,options:{trustedSigners:[signer.address.toLowerCase()]}};}
function provider(bundle){const b=bundle.batch;const log=AVR_EVENTS.encodeEventLog(AVR_EVENTS.getEvent('ReceiptBatchAnchoredV2'),[b.id,b.root,b.publisher,b.leafCount,b.schemaVersion,100]);return {getNetwork:async()=>({chainId:84532n}),getCode:async()=> '0x6001',getBlockNumber:async()=>111,getBlock:async()=>({number:100,hash:blockHash}),getTransactionReceipt:async()=>({status:1,hash:tx,blockNumber:100,blockHash,logs:[{address:CONTRACT,...log}]})};}
test('exact accepted event links to trusted signature and private batch proof',async()=>{const {store,signer,batch,event,options}=await setup();try{const saved=store.evidence(p,event.eventId);const status=await inspectEvidence(event,saved,options);assert.equal(status.state,'batched');assert.equal(status.recordCommitment,true);assert.equal(status.batchMembership,true);assert.equal(batch.broadcast,false);assert.equal((await prepareBatch(store,p,signer,{publisher})),null);assert.equal(store.evidence({...p,tenant:'other'},event.eventId),null);assert.equal((await inspectEvidence({...event,agentRef:'tampered'},saved,options)).state,'invalid-evidence');const changed=structuredClone(saved);changed.bundle.signature='0x'+'00'.repeat(65);assert.equal((await inspectEvidence(event,changed,options)).state,'invalid-evidence');assert.equal((await inspectEvidence(event,saved,{trustedSigners:[]})).state,'untrusted-signer');}finally{store.close();}});
test('Base V2 verification handles confirmations, reorgs, outages, publisher and code mismatch',async()=>{const {store,batch,event,options}=await setup();try{await attachTransaction(store,p,batch.batchId,tx);const saved=store.evidence(p,event.eventId),rpc=provider(saved.bundle),settings={...options,provider:rpc,codeHash:keccak256('0x6001')};assert.equal((await inspectEvidence(event,saved,settings)).state,'confirmed');rpc.getBlockNumber=async()=>99;assert.equal((await inspectEvidence(event,saved,settings)).state,'unavailable');rpc.getBlockNumber=async()=>101;assert.equal((await inspectEvidence(event,saved,settings)).state,'confirming');rpc.getBlock=async()=>({number:100,hash:'0x'+'dd'.repeat(32)});assert.equal((await inspectEvidence(event,saved,settings)).state,'reorg-detected');rpc.getBlock=async()=>{throw Error('offline');};assert.equal((await inspectEvidence(event,saved,settings)).state,'unavailable');const wrong=provider(saved.bundle);const old=wrong.getTransactionReceipt;wrong.getTransactionReceipt=async()=>{const r=await old();const b=saved.bundle.batch;r.logs=[{address:CONTRACT,...AVR_EVENTS.encodeEventLog(AVR_EVENTS.getEvent('ReceiptBatchAnchoredV2'),[b.id,b.root,'0x'+'ee'.repeat(20),b.leafCount,b.schemaVersion,100])}];return r;};assert.equal((await inspectEvidence(event,saved,{...settings,provider:wrong})).state,'verification-failed');assert.equal((await inspectEvidence(event,saved,{...settings,provider:provider(saved.bundle),codeHash:'0x'+'00'.repeat(32)})).state,'verification-failed');rpc.getTransactionReceipt=async()=>null;assert.equal((await inspectEvidence(event,saved,settings)).state,'not-found');}finally{store.close();}});
test('evidence updates are atomic, immutable and revision checked',async()=>{const {store,batch}=await setup();try{const entries=store.batchEvidence(p,batch.batchId);entries[0].bundle.transactions=[tx];entries[1].expectedRevision=999;assert.throws(()=>store.commitEvidence(p,entries),e=>e.status===409);assert.ok(store.batchEvidence(p,batch.batchId).every(e=>e.bundle.transactions.length===0));const edit=store.batchEvidence(p,batch.batchId);edit[0].bundle.receipt.event.type='governance:forged';assert.throws(()=>store.commitEvidence(p,edit),e=>e.status===409);await assert.rejects(attachTransaction(store,{...p,tenant:'other'},batch.batchId,tx),e=>e.status===404);}finally{store.close();}});
test('tenant-scoped evidence route and download disclose only one authorized record',async()=>{const {store,event,options}=await setup();const {createServer}=require('./server.cjs');const token='local-evidence-token-'.repeat(3);const server=createServer(store,[{...p,token,scopes:['read']}],[],store.db,options);await new Promise(r=>server.listen(0,'127.0.0.1',r));try{const url=`http://127.0.0.1:${server.address().port}/v1/evidence/${event.eventId}`;assert.equal((await fetch(url)).status,401);const r=await fetch(url,{headers:{authorization:'Bearer '+token}});assert.equal(r.status,200);const data=await r.json();assert.equal(data.verification.state,'batched');assert.equal(data.evidence.batch.receiptIds,undefined);assert.deepEqual(data.event,event);assert.equal(data.evidence.privateKey,undefined);}finally{await new Promise(r=>server.close(r));store.close();}});
