const test=require('node:test'),assert=require('node:assert/strict'),{EventEmitter}=require('node:events');
const {boundedRpcTransport,createPublisherReviewProvider}=require('./publisher-review-rpc.cjs');
const url='https://rpc.example.test/private-token',req={url,method:'POST',body:Buffer.from(JSON.stringify({jsonrpc:'2.0',id:1,method:'eth_chainId',params:[]})),headers:{'content-type':'application/json'}};
function transport({status=200,chunks=[Buffer.from('{"jsonrpc":"2.0","id":1,"result":"0x14a34"}')],timeout=false}={}){
 let called=0,destroyed=false,timeoutValue;
 const request=(target,options,callback)=>{called++;assert.equal(target.href,url);assert.equal(options.rejectUnauthorized,true);const client=new EventEmitter();client.destroy=()=>{destroyed=true;};client.setTimeout=(ms,fn)=>{timeoutValue=ms;client.timeout=fn;};client.end=body=>{assert.deepEqual(JSON.parse(body),JSON.parse(req.body));queueMicrotask(()=>{if(timeout){client.timeout();return;}const response=new EventEmitter();response.statusCode=status;response.headers={};response.resume=()=>{};response.destroy=()=>{};callback(response);for(const chunk of chunks)response.emit('data',chunk);response.emit('end');});};return client;};
 return {request,send:boundedRpcTransport(url,{request}),get called(){return called;},get destroyed(){return destroyed;},get timeoutValue(){return timeoutValue;}};
}
test('review RPC transport pins HTTPS origin, verifies TLS and returns a bounded response',async()=>{const x=transport(),result=await x.send(req);assert.equal(result.statusCode,200);assert.equal(JSON.parse(Buffer.from(result.body)).result,'0x14a34');assert.equal(x.called,1);assert.equal(x.timeoutValue,5000);});
test('signing, sending, batch, oversized and redirected requests are refused before transport',async()=>{const x=transport();for(const changed of [{url:'https://other.example.test/'},{method:'GET'},{body:Buffer.alloc(32769)},{body:Buffer.from('[{"method":"eth_chainId"}]')},{body:Buffer.from('{"jsonrpc":"2.0","method":"eth_sendRawTransaction"}')},{body:Buffer.from('{"jsonrpc":"2.0","method":"personal_sign"}') }])await assert.rejects(x.send({...req,...changed}),/refused/);assert.equal(x.called,0);});
test('redirects, errors, oversized responses and stalled requests fail without retrying',async()=>{for(const status of [301,302,307,308,401,429,500]){const x=transport({status});await assert.rejects(x.send(req),/HTTP response refused/);assert.equal(x.called,1);}const large=transport({chunks:[Buffer.alloc(1048577)]});await assert.rejects(large.send(req),/response limit/);assert.equal(large.destroyed,true);const stalled=transport({timeout:true});await assert.rejects(stalled.send(req),/timeout/);assert.equal(stalled.called,1);assert.equal(stalled.destroyed,true);});
test('plain HTTP, URL credentials and fragments are refused; provider exposes no transaction methods',()=>{for(const value of ['http://rpc.example.test/','https://user:password@rpc.example.test/','https://rpc.example.test/#token'])assert.throws(()=>boundedRpcTransport(value),/HTTPS/);const provider=createPublisherReviewProvider(url);try{assert.equal(provider.broadcastTransaction,undefined);assert.equal(provider.send,undefined);assert.equal(typeof provider.getNetwork,'function');}finally{provider.destroy();}});
test('SDK adapter reads the real RPC chain response rather than its configured network, with no startup retries',async()=>{for(const hex of ['0x14a34','0x1']){const x=transport({chunks:[Buffer.from(JSON.stringify({jsonrpc:'2.0',id:1,result:hex}))]}),provider=createPublisherReviewProvider(url,{request:x.request});try{assert.equal((await provider.getNetwork()).chainId,BigInt(hex));assert.equal(x.called,1);}finally{provider.destroy();}}});
