'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{Wallet}=require('ethers'),{GovernanceStore}=require('./store'),{DeliveryJournal}=require('./webhook-delivery.cjs'),{RuleEngine}=require('./governance-rules.cjs'),{inspectRuleLinks}=require('./recovery-rule-links.cjs'),{compareRuleEvidence}=require('./recovery-rule-evidence.cjs');
test('signed source/derived evidence distinguishes missing, altered, unsigned, untrusted and uncertain acknowledgements',async()=>{
 const scope={tenant:'synthetic',project:'rule-evidence'},store=new GovernanceStore(':memory:'),journal=new DeliveryJournal(':memory:'),engine=new RuleEngine(journal),signer=Wallet.createRandom();try{
  const source={...require('../../fixtures/governance/paired-model-comparison-v0.1.0-draft.json').events[0],tenantRef:scope.tenant,projectRef:scope.project,eventId:'synthetic-source',result:{status:'failed'}};
  engine.register(scope,{id:'failure',version:1,environment:source.environment,condition:'run-failed',severity:'high'},{actorRef:'synthetic-owner',now:Date.now()-1000});store.ingest(source,scope);engine.process(scope,store.get(scope,source.eventId));await engine.publishDetected(store,scope);await require('./evidence.cjs').prepareBatch(store,scope,signer,{publisher:signer.address,limit:10});
  const holder={};assert.equal(inspectRuleLinks(journal.db,[],100,holder).localLinks,'matched');const ruleRows=holder.rows,entries=store.db.prepare('SELECT e.*,o.status,v.revision,v.batch_id,v.bundle FROM events e JOIN outbox o USING(tenant,project,id) JOIN governance_evidence v USING(tenant,project,id)').all().map(r=>({...r,body:JSON.parse(r.body),received:JSON.parse(r.body).receivedAt,bundle:JSON.parse(r.bundle)})),signers=[signer.address.toLowerCase()];
  const compare=(rows=ruleRows,records=entries,trust=signers)=>compareRuleEvidence(rows,records,trust),matched=await compare();assert.equal(matched.recordingEvidence,'matched');assert.equal(matched.evidenceChecked,2);assert.equal(matched.counts.matchedSources,1);assert.equal(matched.counts.matchedDerived,1);assert.equal(matched.unreferencedRecords,0);
  assert.equal((await compare(ruleRows,entries.filter(r=>r.id!==source.eventId))).counts.missingSources,1);assert.equal((await compare(ruleRows,entries.filter(r=>r.id===source.eventId))).counts.missingPublished,1);
  let changed=structuredClone(entries);changed.find(r=>r.id===source.eventId).body.result.status='completed';assert.equal((await compare(ruleRows,changed)).counts.sourceDigestMismatch,1);
  changed=structuredClone(entries);changed.find(r=>r.id!==source.eventId).body.monitor.severity='critical';assert.equal((await compare(ruleRows,changed)).counts.derivedBodyMismatch,1);
  changed=structuredClone(entries);Object.assign(changed.find(r=>r.id!==source.eventId),{bundle:null,revision:null,batch_id:null,status:'pending'});assert.equal((await compare(ruleRows,changed)).recordingEvidence,'incomplete');assert.equal((await compare(ruleRows,changed)).counts.unsignedEvidence,1);
  assert.equal((await compare(ruleRows,entries,['0x'+'ab'.repeat(20)])).counts.invalidEvidence,2);
  let rows=structuredClone(ruleRows);rows.governance_detected_outbox[0].state='pending';assert.equal((await compare(rows)).counts.acknowledgementRepair,1);assert.equal((await compare(rows,entries.filter(r=>r.id===source.eventId))).counts.unpublishedDerived,1);
  rows=structuredClone(ruleRows);rows.governance_checks[0].assessment='clear';assert.equal((await compare(rows)).counts.assessmentMismatch,1);
  rows=structuredClone(ruleRows);rows.governance_rule_cursors.push({...scope,position:1});assert.equal((await compare(rows)).cursorReconciliation,'sqlite-rowid-mapping-required');await assert.rejects(compareRuleEvidence(ruleRows,entries,signers,0),/bounded duration/);
 }finally{journal.close();store.close();}
});
