'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),{DatabaseSync}=require('node:sqlite'),{Wallet,keccak256}=require('ethers'),{BATCH_ABI,baseBatchId}=require('../../sdk/typescript/base-sepolia-batch-adapter'),{CONTRACT}=require('./evidence.cjs'),{VERSION}=require('../../sdk/typescript/verification-receipt'),{reviewWorkerSpend}=require('./recovery-worker-spend.cjs');
async function fixture(){const directory=fs.mkdtempSync(path.join(os.tmpdir(),'synthetic-spend-review-')),file=path.join(directory,'worker.sqlite'),db=new DatabaseSync(file),signer=Wallet.createRandom(),expected={tenant:'synthetic',project:'test',publisher:signer.address.toLowerCase(),recorder:Wallet.createRandom().address.toLowerCase()},root='0x'+'aa'.repeat(32),id=baseBatchId(CONTRACT,expected.publisher,root),raw=await signer.signTransaction({chainId:84532,type:2,nonce:7,to:CONTRACT,data:BATCH_ABI.encodeFunctionData('anchorBatch',[root,2,VERSION]),value:0,gasLimit:100000,maxFeePerGas:100,maxPriorityFeePerGas:1}),now=Date.now(),job={id,raw,hash:keccak256(raw),nonce:7,state:'confirmed',reserve:'10001000',signedAt:now-1000};
 db.exec("CREATE TABLE governance_environment(name TEXT); INSERT INTO governance_environment VALUES('test'); CREATE TABLE governance_recovery_gate(singleton INTEGER PRIMARY KEY,state TEXT); INSERT INTO governance_recovery_gate VALUES(1,'review-required'); CREATE TABLE config(id INTEGER PRIMARY KEY,body TEXT); CREATE TABLE jobs(id TEXT PRIMARY KEY,body TEXT)");db.prepare('INSERT INTO config VALUES(1,?)').run(JSON.stringify({scope:{tenant:expected.tenant,project:expected.project},publisher:expected.publisher,recorder:expected.recorder,contract:CONTRACT,chain:84532}));db.prepare('INSERT INTO jobs VALUES(?,?)').run(id,JSON.stringify(job));
 const options={environment:'test',file,expected,now,policy:{batchSize:1000,maxTransactionsPerHour:10,maxGasPriceWei:'100',dailyReservationWei:'100000000',l1AllowanceWei:'1000'}};
 return {options,db,job,signer,write(value){db.prepare('UPDATE jobs SET body=? WHERE id=?').run(JSON.stringify(value),id);},close(){db.close();const resolved=fs.realpathSync(directory);if(path.dirname(resolved)!==fs.realpathSync(os.tmpdir())||!path.basename(resolved).startsWith('synthetic-spend-review-'))throw Error('Unsafe synthetic cleanup target');fs.rmSync(resolved,{recursive:true,force:true});}};
}
test('actual signed execution ceiling and saved reservation compare read-only with current policy',async()=>{
 const f=await fixture();try{const before=fs.readFileSync(f.options.file),result=reviewWorkerSpend(f.options);assert.equal(result.spendReview,'compatible-with-recorded-state');assert.equal(result.recentRequiredWei,'10001000');assert.equal(result.totalExecutionCeilingWei,'10000000');assert.equal(result.counts.recentHour,1);assert.equal(result.actualFees,'not-reconciled');assert.equal(result.activation,'review-required');assert.deepEqual(fs.readFileSync(f.options.file),before);for(const hidden of [f.job.raw,f.job.hash,f.options.expected.publisher])assert.ok(!JSON.stringify(result).includes(hidden));
  assert.equal(reviewWorkerSpend({...f.options,policy:{...f.options.policy,l1AllowanceWei:'2000'}}).counts.belowCurrentReserve,1);assert.equal(reviewWorkerSpend({...f.options,policy:{...f.options.policy,maxGasPriceWei:'99'}}).counts.aboveCurrentFee,1);assert.equal(reviewWorkerSpend({...f.options,policy:{...f.options.policy,batchSize:1}}).counts.aboveCurrentBatchSize,1);assert.equal(reviewWorkerSpend({...f.options,policy:{...f.options.policy,dailyReservationWei:'1'}}).dayExceeded,true);
  const root='0x'+'bb'.repeat(32),id=baseBatchId(CONTRACT,f.options.expected.publisher,root),raw=await f.signer.signTransaction({chainId:84532,type:2,nonce:8,to:CONTRACT,data:BATCH_ABI.encodeFunctionData('anchorBatch',[root,2,VERSION]),value:0,gasLimit:100000,maxFeePerGas:100,maxPriorityFeePerGas:1});f.db.prepare('INSERT INTO jobs VALUES(?,?)').run(id,JSON.stringify({...f.job,id,raw,hash:keccak256(raw),nonce:8}));const limited=reviewWorkerSpend({...f.options,policy:{...f.options.policy,maxTransactionsPerHour:1}});assert.equal(limited.counts.recentHour,2);assert.equal(limited.hourExceeded,true);assert.equal(limited.spendReview,'requires-reconciliation');
 }finally{f.close();}
});
test('missing/understated reservations, future times and malformed policy fail reconciliation',async()=>{
 const f=await fixture();try{for(const reserve of [undefined,'0','-1','1','x'.repeat(80)]){f.write({...f.job,reserve});const result=reviewWorkerSpend(f.options);assert.equal(result.spendReview,'requires-reconciliation');assert.ok(result.counts.invalidReservation+result.counts.belowCurrentReserve>0);}for(const signedAt of [undefined,-1,f.options.now+1]){f.write({...f.job,signedAt});assert.equal(reviewWorkerSpend(f.options).counts.invalidSigningTime,1);}f.write({...f.job,signedAt:f.options.now-86400001});assert.equal(reviewWorkerSpend(f.options).counts.recentDay,0);
  assert.throws(()=>reviewWorkerSpend({...f.options,policy:{...f.options.policy,paused:false}}),/policy/);assert.throws(()=>reviewWorkerSpend({...f.options,policy:{...f.options.policy,maxGasPriceWei:'9'.repeat(79)}}),/policy/);f.write({...f.job,nonce:8});assert.throws(()=>reviewWorkerSpend(f.options),/integrity/);
 }finally{f.close();}
});
