'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{DatabaseSync}=require('node:sqlite'),{Wallet,keccak256}=require('ethers'),{reviewWorkerJournal,inspectJob}=require('./recovery-worker-review.cjs'),{CONTRACT}=require('./evidence.cjs'),{BATCH_ABI,baseBatchId}=require('../../sdk/typescript/base-sepolia-batch-adapter'),{VERSION}=require('../../sdk/typescript/verification-receipt');
test('restored signed worker bytes validate without broadcast and detect wrong hash/nonce/publisher',async()=>{
 const signer=Wallet.createRandom(),expected={tenant:'synthetic',project:'test',publisher:signer.address.toLowerCase(),recorder:Wallet.createRandom().address.toLowerCase()},root='0x'+'aa'.repeat(32),id=baseBatchId(CONTRACT,expected.publisher,root),data=BATCH_ABI.encodeFunctionData('anchorBatch',[root,1,VERSION]),raw=await signer.signTransaction({type:2,chainId:84532,nonce:7,to:CONTRACT,data,value:0,gasLimit:100000,maxFeePerGas:100,maxPriorityFeePerGas:1}),job={id,raw,hash:keccak256(raw),nonce:7,state:'confirmed'},row={id,body:JSON.stringify(job)};
 assert.equal(inspectJob(row,expected).kind,'signed');for(const changed of [{...job,nonce:8},{...job,hash:'0x'+'00'.repeat(32)},{...job,raw:'0x1234'},{...job,id:'0x'+'bb'.repeat(32)}])assert.equal(inspectJob({id,body:JSON.stringify(changed)},expected).kind,'invalid');assert.equal(inspectJob(row,{...expected,publisher:Wallet.createRandom().address}).kind,'invalid');
 const directory=fs.mkdtempSync(path.join(os.tmpdir(),'synthetic-worker-review-')),file=path.join(directory,'worker.sqlite'),db=new DatabaseSync(file);
 try{
  db.exec("CREATE TABLE governance_environment(name TEXT); INSERT INTO governance_environment VALUES('test'); CREATE TABLE governance_recovery_gate(singleton INTEGER PRIMARY KEY CHECK(singleton=1),state TEXT); INSERT INTO governance_recovery_gate VALUES(1,'review-required'); CREATE TABLE config(id INTEGER PRIMARY KEY,body TEXT); CREATE TABLE jobs(id TEXT PRIMARY KEY,body TEXT)");db.prepare('INSERT INTO config VALUES(1,?)').run(JSON.stringify({scope:{tenant:expected.tenant,project:expected.project},publisher:expected.publisher,recorder:expected.recorder,contract:CONTRACT,chain:84532}));db.prepare('INSERT INTO jobs VALUES(?,?)').run(id,row.body);
  const before=fs.readFileSync(file),result=reviewWorkerJournal({environment:'test',file,expected});assert.equal(result.journalIntegrity,'passed');assert.equal(result.counts.signed,1);assert.equal(result.networkReconciliation,'not-checked');assert.equal(result.activation,'review-required');assert.ok(!JSON.stringify(result).includes(raw));assert.deepEqual(fs.readFileSync(file),before);assert.throws(()=>reviewWorkerJournal({environment:'dev',file,expected}),/mismatch/);
  const recovery=require('./recovery.cjs'),key=require('node:crypto').randomBytes(32),archive=await recovery.createBackup({environment:'test',files:[{role:'worker',path:file}],outputRoot:path.join(directory,'archives'),key,consistency:'quiesced'}),restored=await recovery.restoreBackup({environment:'test',directory:archive.directory,outputRoot:path.join(directory,'restores'),key});key.fill(0);
  const restoredFile=path.join(restored.directory,'worker.sqlite'),restoredResult=reviewWorkerJournal({environment:'test',file:restoredFile,expected});assert.equal(restoredResult.journalIntegrity,'passed');assert.equal(restoredResult.snapshotDigest,result.snapshotDigest);assert.equal(restoredResult.activation,'review-required');assert.equal(restoredResult.networkReconciliation,'not-checked');assert.throws(()=>require('./environment.cjs').bindSqlite(restoredFile,'test'),/reviewed recovery/);
  const otherRoot='0x'+'bb'.repeat(32),otherId=baseBatchId(CONTRACT,expected.publisher,otherRoot),otherRaw=await signer.signTransaction({type:2,chainId:84532,nonce:7,to:CONTRACT,data:BATCH_ABI.encodeFunctionData('anchorBatch',[otherRoot,1,VERSION]),value:0,gasLimit:100000,maxFeePerGas:100,maxPriorityFeePerGas:1});db.prepare('INSERT INTO jobs VALUES(?,?)').run(otherId,JSON.stringify({id:otherId,raw:otherRaw,hash:keccak256(otherRaw),nonce:7,state:'submitted'}));assert.throws(()=>reviewWorkerJournal({environment:'test',file,expected,maxJobs:1}),/full-review limit/);assert.equal(reviewWorkerJournal({environment:'test',file,expected}).counts.nonceConflicts,1);assert.equal(reviewWorkerJournal({environment:'test',file,expected}).journalIntegrity,'failed');
 }finally{db.close();const resolved=fs.realpathSync(directory);if(path.dirname(resolved)!==fs.realpathSync(os.tmpdir())||!path.basename(resolved).startsWith('synthetic-worker-review-'))throw Error('Unsafe synthetic cleanup target');fs.rmSync(resolved,{recursive:true,force:true});}
});
