'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{Wallet,keccak256}=require('ethers'),{GovernanceStore}=require('./store'),{prepareBatch,CONTRACT}=require('./evidence.cjs'),{compareBatch}=require('./recovery-worker-evidence.cjs'),{AVR_EVENTS}=require('../../sdk/typescript/avr-anchor-verifier');
test('journal batch reconciliation verifies every receipt and treats historical confirmation as unresolved without RPC',async()=>{
 const store=new GovernanceStore(':memory:'),signer=Wallet.createRandom(),p={tenant:'org-demo',project:'claims-governance-demo'},expected={...p,publisher:signer.address.toLowerCase(),recorder:signer.address.toLowerCase()};try{
  for(const e of require('../../fixtures/governance/paired-model-comparison-v0.1.0-draft.json').events.slice(0,3))store.ingest(e,p);
  const batch=await prepareBatch(store,p,signer,{publisher:signer.address}),records=store.batchEvidence(p,batch.batchId).map(e=>({event:store.get(p,e.id),bundle:e.bundle})),raw=await signer.signTransaction({chainId:84532,type:2,nonce:7,to:CONTRACT,data:batch.transaction.data,value:0,gasLimit:100000,maxFeePerGas:100,maxPriorityFeePerGas:1}),job={id:batch.batchId,raw,hash:keccak256(raw),nonce:7,state:'confirmed'},row={id:job.id,body:JSON.stringify(job)};
  const offline=await compareBatch(records,row,expected);assert.equal(offline.state,'submitted-offline');assert.equal(offline.transactionLinkRepairRequired,true);assert.equal((await compareBatch(records.slice(0,2),row,expected)).state,'batch-incomplete');
  const changed=structuredClone(records);changed[2].bundle.signature='0x'+'00'.repeat(65);assert.equal((await compareBatch(changed,row,expected)).state,'invalid-evidence');const divergence=structuredClone(records);divergence[0].bundle.transactions=['0x'+'aa'.repeat(32)];assert.equal((await compareBatch(divergence,row,expected)).state,'transaction-divergence');
  const b=records[0].bundle.batch,blockHash='0x'+'cc'.repeat(32),log=AVR_EVENTS.encodeEventLog(AVR_EVENTS.getEvent('ReceiptBatchAnchoredV2'),[b.id,b.root,b.publisher,b.leafCount,b.schemaVersion,100]),provider={getNetwork:async()=>({chainId:84532n}),getCode:async()=> '0x6001',getBlockNumber:async()=>111,getBlock:async()=>({number:100,hash:blockHash}),getTransactionReceipt:async()=>({status:1,hash:job.hash,blockNumber:100,blockHash,logs:[{address:CONTRACT,...log}]})};
  assert.equal((await compareBatch(records,row,expected,{provider,codeHash:keccak256('0x6001')})).state,'confirmed');provider.getBlock=async()=>({number:100,hash:'0x'+'dd'.repeat(32)});assert.equal((await compareBatch(records,row,expected,{provider,codeHash:keccak256('0x6001')})).state,'reorg-detected');provider.getBlock=async()=>{throw Error('offline');};assert.equal((await compareBatch(records,row,expected,{provider,codeHash:keccak256('0x6001')})).state,'unavailable');
 }finally{store.close();}
});
