'use client';
import { useEffect, useState } from 'react';
type Event = {eventId:string;eventType:string;occurredAt:string;receivedAt:string;agentRef?:string;caseRef?:string;source:{kind:string;keyRef:string};model?:{deploymentRef:string;configVersion:string};result?:{predictedLabel?:string;status?:string};policy?:{decision?:string;policyRef:string;version:string};outcome?:{label:string;labelSource:string;rubricVersion?:string;forEventId:string};monitor?:{signalCode:string;severity:string;disposition?:string};evidenceRefs?:{role:string;commitment:string;availability:string}[]};
type Model={key:string;deployment:string;configuration:string;task:string;runs:number;labelled:number;correct:number;pending:number;conflicting:number;excluded:number;accuracy:number|null;accuracyStatus:string;p95LatencyMs:number|null;rubrics:string[]};
type Report={eventCount:number;kpis:{agentsReporting:number;runs:number;modelDeployments:number;policyEvaluations:number;denied:number;reviewedLabels:number;openAlerts:number};models:Model[];trends:{day:string;runs:number;failures:number}[];alerts:{eventId:string;agent:string;occurredAt:string;signal:string;severity:string;disposition:string;source:string;expectedDigest:string|null;observedDigest:string|null}[];assurance:Record<string,string>};
type View={key:string;report:Report;events:Event[];from:string;to:string;detailLimit:number};
type Demo={synthetic:boolean;asOf:string;labelPolicy:string;views:View[]};
const tabs=['Overview','Decisions','Models','Incidents','Reports','Usage'];
const number=(n:number)=>n.toLocaleString('en-GB');
const percent=(n:number|null)=>n===null?'Awaiting evidence':`${(n*100).toFixed(1)}%`;
function ActivityChart({points}:{points:Report['trends']}){
 const max=Math.max(1,...points.map(p=>p.runs));const xy=points.map((p,i)=>`${35+i*610/Math.max(1,points.length-1)},${160-p.runs/max*120}`).join(' ');
 return <><svg viewBox="0 0 680 200" role="img" aria-label="Daily recorded runs in the selected period" className="gp-chart"><title>Daily recorded runs; synthetic data</title>{[0,1,2].map(n=><g key={n}><line x1="35" x2="645" y1={40+n*60} y2={40+n*60} stroke="#dce5e7"/><text x="0" y={44+n*60} fill="#647782" fontSize="11">{Math.round(max*(1-n/2))}</text></g>)}<polygon points={`35,160 ${xy} 645,160`} fill="#e4eeeb"/><polyline points={xy} fill="none" stroke="#247568" strokeWidth="3"/>{points.map((p,i)=><g key={p.day}><circle cx={35+i*610/Math.max(1,points.length-1)} cy={160-p.runs/max*120} r="3" fill="#247568"><title>{p.day}: {p.runs} runs</title></circle>{i%Math.max(1,Math.floor(points.length/5))===0&&<text x={35+i*610/Math.max(1,points.length-1)} y="187" fontSize="11" textAnchor="middle" fill="#647782">{p.day.slice(5)}</text>}</g>)}</svg><details className="gp-chart-data"><summary>View chart data</summary><table><thead><tr><th>Date (UTC)</th><th>Runs</th></tr></thead><tbody>{points.map(p=><tr key={p.day}><td>{p.day}</td><td>{p.runs}</td></tr>)}</tbody></table></details></>;
}
export default function GovernancePortal(){
 const [data,setData]=useState<Demo|null>(null),[error,setError]=useState(''),[tab,setTab]=useState('Overview'),[days,setDays]=useState(14),[model,setModel]=useState('all'),[search,setSearch]=useState(''),[selected,setSelected]=useState<Event|null>(null);
 useEffect(()=>{const controller=new AbortController();fetch('/governance-demo.json',{signal:controller.signal}).then(r=>{if(!r.ok)throw new Error('The demonstration data could not be loaded.');return r.json();}).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>controller.abort();},[]);
 const view=data?.views.find(v=>v.key===`${days}:${model}`),report=view?.report;
 const rows=view?.events.filter(e=>`${e.eventId} ${e.agentRef||''} ${e.caseRef||''} ${e.eventType}`.toLowerCase().includes(search.toLowerCase()))||[];
 function exportReport(){if(view)window.location.assign(`/api/governance-demo-report?days=${days}&deployment=${model}&format=json`);}
 function exportCsv(){if(view)window.location.assign(`/api/governance-demo-report?days=${days}&deployment=${model}&format=csv`);}
 return <div className="gp-shell"><aside className="gp-sidebar"><a href="/" className="gp-brand"><span>◒</span> Orvessian</a><div className="gp-workspace"><small>WORKSPACE</small><strong>Northstar operations</strong><span>Governance demonstration</span></div><nav aria-label="Workspace sections">{tabs.map((item,i)=><button key={item} aria-current={tab===item?'page':undefined} onClick={()=>{setTab(item);setSelected(null);}}><span aria-hidden="true">{['◈','≡','▦','◇','▤','◴'][i]}</span>{item}{item==='Incidents'&&report&&<b>{report.kpis.openAlerts}</b>}</button>)}</nav><div className="gp-side-bottom"><span className="gp-dot"/> Structured records only<p>Source conversations and documents stay with the customer.</p><a href="/workspace">Customer sign-in ↗</a><a href="/products/governance-preview">Product & plans preview ↗</a><a href="/explorer">Public testnet explorer ↗</a></div></aside>
 <main className="gp-main"><div className="gp-demo-banner"><strong>Interactive product preview</strong><span>All activity is synthetic · No customer account or live monitoring connected</span></div><header className="gp-header"><div><p className="gp-eyebrow">NORTHSTAR / GOVERNANCE</p><h1>{tab==='Overview'?'Your AI, in view.':tab}</h1><p>{tab==='Overview'?'Understand the decisions. Follow the evidence. Act on the exceptions.':'Explore the records behind your governance workspace.'}</p></div><button className="gp-primary" onClick={exportReport} disabled={!report}>Export report ↓</button></header>
 <div className="gp-toolbar"><div className="gp-filters"><label>Period<select value={days} onChange={e=>{setDays(Number(e.target.value));setSelected(null);}}><option value={7}>Last 7 demo days</option><option value={14}>Last 14 demo days</option></select></label><label>Model deployment<select value={model} onChange={e=>{setModel(e.target.value);setSelected(null);}}><option value="all">All deployments</option><option value="claims-model-v1">Claims model v1</option><option value="claims-model-v2">Claims model v2</option></select></label></div><span>{view?`${view.from.slice(0,10)} – 2026-09-14 · UTC`:'Loading workspace…'}</span></div>
 {error&&<div role="alert" className="gp-alert">{error} Refresh the page to retry.</div>}{!report&&!error&&<p role="status">Loading governance reports…</p>}
 {report&&view&&<>
 {(tab==='Overview'||tab==='Usage')&&<section className="gp-kpis" aria-label="Key performance indicators">{[[number(report.kpis.agentsReporting),'Agents reporting','Seen in the selected run records'],[number(report.kpis.runs),'Model runs recorded',`${number(report.eventCount)} structured events incl. outcomes`],[number(report.kpis.reviewedLabels),'Adjudicated outcomes','Labels available at snapshot time'],[number(report.kpis.openAlerts),'Open incident records','Submitted monitor alerts']].map(([value,label,note])=><article key={label}><p>{label}</p><strong>{value}</strong><small>{note}</small></article>)}</section>}
 {tab==='Overview'&&<><div className="gp-two-col"><section className="gp-panel"><div className="gp-panel-head"><div><h2>Model activity</h2><p>Recorded model runs per day</p></div><span className="gp-pill">{days} days</span></div><ActivityChart points={report.trends}/></section><section className="gp-panel gp-attention"><p className="gp-eyebrow">NEEDS ATTENTION</p><h2>{report.kpis.openAlerts?`${report.kpis.openAlerts} configuration alerts`:'No alerts in this view'}</h2><p>Compare observed settings with the approved configuration. Follow the incident record to understand the source and response.</p><button onClick={()=>setTab('Incidents')}>Review incidents →</button><div className="gp-monitor-note"><strong>Monitoring coverage: not established</strong><p>Heartbeat inventory is not connected. Reporting agents are not a live count of running agents.</p></div></section></div></>}
 {(tab==='Overview'||tab==='Models')&&<section className="gp-panel"><div className="gp-panel-head"><div><h2>Model performance</h2><p>Accuracy against adjudicated labels · minimum 30 eligible cases per cohort</p></div><button className="gp-link" onClick={()=>setTab(tab==='Models'?'Reports':'Models')}>{tab==='Models'?'Report definitions':'Explore models'} →</button></div><div className="gp-table-wrap"><table><thead><tr><th>Deployment / task</th><th>Runs</th><th>Adjudicated accuracy</th><th>Correct / labelled</th><th>p95 latency</th></tr></thead><tbody>{report.models.map(m=><tr key={m.key}><td><strong>{m.deployment}</strong><small>{m.task} · {m.configuration}</small></td><td>{number(m.runs)}</td><td><strong>{percent(m.accuracy)}</strong><div className="gp-meter"><span style={{width:`${(m.accuracy||0)*100}%`}}/></div><small>{m.accuracyStatus}</small></td><td>{m.correct} / {m.labelled}<small>{m.pending} pending · {m.conflicting} conflicting</small></td><td>{m.p95LatencyMs===null?'Unavailable':`${number(m.p95LatencyMs)} ms`}</td></tr>)}</tbody></table></div><p className="gp-footnote">These are synthetic descriptive cohorts. A higher score alone does not establish the effect of switching models. Evaluator, rubric, task mix and labelled-case coverage matter.</p></section>}
 {tab==='Decisions'&&<section className="gp-panel"><div className="gp-panel-head"><div><h2>Decision and outcome records</h2><p>Latest {view.detailLimit} records in this filtered demonstration · {number(report.eventCount)} total</p></div><label className="gp-search">Search records<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Agent, case or event ID"/></label></div><div className="gp-table-wrap"><table><thead><tr><th>Recorded at (UTC)</th><th>Record</th><th>Agent / case</th><th>Outcome</th></tr></thead><tbody>{rows.slice(0,50).map(e=><tr key={e.eventId}><td>{e.occurredAt.slice(5,16).replace('T',' ')}</td><td><button className="gp-link" onClick={()=>setSelected(e)}>{e.eventType.replace('ai.','')}</button><small>{e.eventId}</small></td><td>{e.agentRef||(e.source.kind==='human-reviewer'?'Review team':'Agent not supplied')}<small>{e.caseRef||'Operational observation'}</small></td><td>{e.outcome?.label||e.result?.predictedLabel||e.policy?.decision||e.monitor?.disposition||'Observed'}</td></tr>)}</tbody></table></div>{!rows.length&&<p>No records match your search.</p>}<p className="gp-footnote">Showing up to 50 matching records from the latest 100. Full pagination is available through the local development API.</p></section>}
 {tab==='Incidents'&&<section className="gp-panel"><div className="gp-panel-head"><div><h2>Control exceptions</h2><p>Recorded alerts and their submitted disposition</p></div><span className="gp-pill">{report.alerts.length} records</span></div>{report.alerts.length?report.alerts.map(a=><article className="gp-incident" key={a.eventId}><div><span className="gp-severity">{a.severity}</span><span className="gp-pill">{a.disposition}</span><h3>{a.signal.replaceAll('-',' ')}</h3><p>{a.agent} · {a.occurredAt.slice(0,10)} · {a.source}</p><details><summary>Inspect the evidence</summary><dl><dt>Approved configuration</dt><dd>{a.expectedDigest||'Not supplied'}</dd><dt>Observed configuration</dt><dd>{a.observedDigest||'Not supplied'}</dd><dt>Record ID</dt><dd>{a.eventId}</dd></dl><p>Source identity is declared. Signature verification and runtime attestation appraisal are not connected in this preview. A mismatch is a signal to investigate, not proof of malicious intent.</p></details></div></article>):<p>No incident records match the selected filter.</p>}</section>}
 {tab==='Reports'&&<><section className="gp-panel"><h2>Reports you can inspect and reproduce</h2><p>Exports include the date range, snapshot time, cohort counts, metric definitions and assurance status. Download the supporting synthetic records to reproduce the report.</p><div className="gp-report-actions"><button className="gp-primary" onClick={exportReport}>Download governance report · JSON</button><button onClick={exportCsv}>Download model comparison · CSV</button><a className="gp-link" href="/governance-demo-events.json" download>Download supporting events · JSON ↓</a></div></section><section className="gp-panel"><h2>What each number means</h2><dl className="gp-definitions"><dt>Adjudicated accuracy</dt><dd>Correct predicted labels / eligible linked human or calibrated labels. Conflicts, mixed evaluator versions and fewer than 30 cases suppress the displayed rate.</dd><dt>Policy evaluations</dt><dd>{number(report.kpis.policyEvaluations)} recorded checks, including {report.kpis.denied} denials. This is not proof that every action was checked.</dd><dt>Reporting agents</dt><dd>Distinct agent IDs in the selected run records. Live inventory and heartbeat coverage remain unavailable.</dd><dt>Evidence integrity</dt><dd>Demo events are unanchored and signatures are not verified. The existing public explorer is a separate Base Sepolia verification view.</dd><dt>Source content</dt><dd>Only registered structured governance fields are retained. Conversations, prompts, files and raw sensor data remain in customer systems.</dd></dl></section></>}
 {tab==='Usage'&&<section className="gp-panel"><h2>Consumption that is easy to understand</h2><p>This view contains {number(report.eventCount)} structured events for {number(report.kpis.runs)} model runs. A run can create several events: policy checks, outcomes and alerts are distinct records.</p><div className="gp-two-col"><article><h3>Proposed usage unit</h3><p>One durably accepted governance event. Identical retries should not be counted twice. The batch size used for Base anchoring is a separate operational measure.</p></article><article><h3>No active billing</h3><p>This demonstration has no subscription, balance or invoices. Plan allowances, currency and prices remain to be decided from measured costs.</p><a className="gp-link" href="/products/governance-preview">View proposed plan structure →</a></article></div></section>}
 <footer className="gp-footer"><span>Demo snapshot · 16 September 2026</span><span>Unanchored · Signatures unchecked · Customer-held source content</span></footer>
 </>}
 {selected&&<section className="gp-detail" aria-label="Record detail"><button onClick={()=>setSelected(null)} className="gp-close">Close ×</button><p className="gp-eyebrow">RECORD DETAIL</p><h2>{selected.eventType.replace('ai.','')}</h2><dl><dt>Event ID</dt><dd>{selected.eventId}</dd><dt>Claimed event time</dt><dd>{selected.occurredAt}</dd><dt>Received time</dt><dd>{selected.receivedAt}</dd><dt>Source</dt><dd>{selected.source.kind}</dd><dt>Model deployment</dt><dd>{selected.model?.deploymentRef||'Linked through case/run'}</dd><dt>Outcome</dt><dd>{selected.outcome?.label||selected.result?.predictedLabel||'Not supplied'}</dd><dt>Verification</dt><dd>Unanchored; source signature not verified</dd></dl><details><summary>Structured event data</summary><pre>{JSON.stringify(selected,null,2)}</pre></details><p>No underlying conversation or document is held here.</p></section>}
 </main></div>;
}
