import { Footer, PageHeader } from "../components";
import { AgentGovernanceStory } from "../agent-governance-story";
import { PlatformPreview } from "../platform-preview";
export const metadata={title:"AI governance platform | Orvessian",description:"Understand agent activity, investigate decisions and independently check governance evidence.",openGraph:{images:[]},twitter:{images:[]}};
const workflows=[
 ["Activity & decisions","Understand the work across your AI operations.","Review agents reporting in the selected window, decision activity and model deployments. Recorded activity gives teams a common starting point; it is not automatic discovery of every running agent."],
 ["Outcomes & comparisons","See what changed when the model changed.","Compare compatible labelled outcomes across deployment cohorts. Keep sample sizes, missing outcomes and evaluator definitions visible. A comparison shows a difference, not proof that a model change caused it."],
 ["Incidents & investigations","Bring the context into the conversation.","Review submitted incident and control observations alongside individual records. Source material stays in customer systems. Automated detection, notifications and incident assignment are planned additions."],
 ["Evidence & verification","Give reviewers something they can check.","In the authenticated pilot, open a record’s signed receipt, Merkle membership proof and Base verification state. Export record-specific evidence for independent checking without disclosing other records in its batch."]
];
export default function Product(){return <main className="platform-site"><PageHeader label="The Orvessian platform" title="Agent governance, from activity to accountability."><p>A governance workspace for the people responsible for AI activity, decisions and outcomes. Backed by evidence they can independently check.</p><div className="actions"><a className="button primary" href="/portal">Explore the synthetic demo ↗</a><a href="/status">Current readiness →</a></div></PageHeader>
 <section className="platform-section platform-workflow"><div><p className="eyebrow">From overview to evidence</p><h2>The daily view.<br/>The decision detail.<br/>The supporting record.</h2><p>Give operations a clearer view of activity, engineering a way to compare outcomes, and governance reviewers a path to the evidence.</p><p>Illustrative preview shown. The public demo uses synthetic data; authenticated evidence verification is in private testnet validation.</p></div><PlatformPreview/></section>
 <section className="platform-section"><div className="platform-cards product-capabilities">{workflows.map(([label,title,copy])=><article key={label}><p className="eyebrow">{label}</p><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
 <AgentGovernanceStory/><section className="platform-evidence"><div><p className="eyebrow">The Orvessian difference</p><h2>A report you can explore.<br/><em>A record you can verify.</em></h2><p>Cryptographic commitments on the Base blockchain create a public reference for private evidence. Authorised reviewers can detect changes to anchored records by checking the disclosed record and proof.</p><a className="button primary" href="/explorer">Inspect the public testnet anchors →</a></div><div><h3>Private evidence. Public commitments.</h3><p>Structured records, signatures and proof openings are held off chain under access controls. A batch commitment goes on chain, rather than your source conversations or documents.</p><h3>Clear checks, with clear limits.</h3><p>The portal separates record integrity, recording-service signature, batch membership and chain confirmation. A valid anchor does not prove source truth, capture completeness or the safety of a decision. The entire application and database are not immutable.</p></div></section>
 <section className="platform-section platform-next"><div><p className="eyebrow">Next on the roadmap</p><h2>Build the governance loop.</h2></div><div><p>Agent ownership and heartbeats. Configurable thresholds and alert delivery. Incident acknowledgment and resolution. Saved views and scheduled reports. Easier integration with existing agent telemetry.</p><p>These are planned capabilities. Production identity, storage, backups and security validation remain release gates.</p><a className="button primary" href="/products/governance-preview">See proposed subscription plans →</a></div></section><Footer/></main>;}
