import Link from "next/link";
import { Footer, PageHeader } from "../components";
import { EvidenceBoundary } from "../evidence-boundary";
export const metadata = { title: "Product | Orvessian", description: "A clear record behind autonomous work.", openGraph: { images: [] }, twitter: { images: [] } };
export default function Product() { return <main><PageHeader label="The product" title="A clear record behind the action."><p>Connect the work an agent does to the evidence and decisions people need to inspect.</p></PageHeader><section className="foundation-content"><p className="eyebrow">One foundation. Three connected layers.</p><div className="foundation-grid">
<article><span className="stage-label">Local alpha</span><h2>Receipts</h2><p>Signed, portable records that bind an event to evidence commitments. The reference tooling creates receipts and lets developers check specific properties.</p><Link href="/developers">Explore the tooling →</Link></article>
<article><span className="stage-label">Product direction</span><h2>Review</h2><p>A human-readable experience for mandates, exceptions and selective evidence disclosure. People review the consequential decisions, not every routine step.</p><Link href="/in-action">Follow an example →</Link></article>
<article><span className="stage-label">Development infrastructure</span><h2>Network</h2><p>An independent EVM-compatible L1 direction for shared anchoring and verification. Development experiments are not a production network.</p><Link href="/technology">Understand the architecture →</Link></article></div></section>
<EvidenceBoundary/><section className="foundation-band"><div><p className="eyebrow">The first useful workflow</p><h2>A recommendation.<br/>An exception.<br/>A decision with a history.</h2></div><div><p>Our starting point is enterprise agent work where someone already needs to inspect the evidence. In the supplier-assessment story, the agent prepares a recommendation while a person decides whether the material supports acceptance.</p><p>The aim is a clearer hand-off between teams—not a claim that an automated record can make every business decision correct.</p><Link className="button primary" href="/in-action">Follow the supplier assessment →</Link></div></section><section className="foundation-content narrow"><h2>Give every hand-off an accountable owner.</h2><p>Orvessian is not an agent runtime. Your application executes the work and enforces permissions. The verification layer connects records, authority evidence and checks across that workflow.</p><div className="responsibility-list"><article><h3>The application enforces.</h3><p>It limits tools, permissions and actions. A recorded mandate cannot stop a runtime that ignores it.</p></article><article><h3>The organisation decides.</h3><p>It sets review criteria and appoints the people authorised to accept, reject or request more evidence.</p></article><article><h3>The verifier checks.</h3><p>It evaluates a specific claim against supplied evidence. Missing material and unsupported checks must remain visible.</p></article></div><div className="actions"><Link className="button primary" href="/in-action">Follow the complete story →</Link><Link className="arrow-link" href="/status">What exists today</Link></div></section><Footer/></main>; }
