import { Footer, PageHeader } from "../components";
import { EvidenceBoundary } from "../evidence-boundary";
import { StoryExperience } from "../story-experience";

export const metadata = { title: "Examples | Orvessian", description: "A simple example of authority, an exception and a decision around autonomous work.", openGraph: { images: [] }, twitter: { images: [] } };

const chapters = [
  { id: "brief", title: "The team sets the brief.", role: "Operations lead", copy: "Prepare a supplier recommendation using approved sources. Check the required documents. Do not place an order or accept commercial terms. The team delegates the research, not the final commitment.", record: "What the record should retain", items: ["The brief and its version", "The responsible organisation and agent", "The scope and approval boundary"] },
  { id: "work", title: "The agent does the groundwork.", role: "Research agent", copy: "The agent gathers the permitted documents, compares them with the checklist and drafts a recommendation. The useful work moves forward without a person reviewing every search or extraction.", record: "Evidence behind the recommendation", items: ["Source document versions", "The checks applied to each document", "The draft recommendation"] },
  { id: "exception", title: "One document stops the approval.", role: "Workflow rule", copy: "A required insurance certificate has expired. The recommendation may be ready, but the evidence is not. In this scenario, the application routes the exception to a person and holds acceptance.", record: "The exception, made visible", items: ["Required document: insurance certificate", "Check result: expired", "Acceptance: awaiting review"] },
  { id: "review", title: "A person makes the consequential call.", role: "Authorised reviewer", copy: "The reviewer sees the relevant document, the rule it failed and the agent’s recommendation. They can request an update, accept suitable evidence or reject the recommendation. Silence is not approval.", record: "What the reviewer stands behind", items: ["Their decision and stated reason", "The exact evidence version reviewed", "Their identity and relevant authority"] },
];

export default function UseCases() {
  return <main><PageHeader label="Examples / an illustrative supplier assessment" title="A simple job. A clear decision history."><p>Follow one example from a clear brief to a decision someone can explain: what the agent could do, what stopped the workflow and who made the call.</p></PageHeader>
    <StoryExperience/>
    <nav className="chapter-nav" aria-label="Story chapters"><a href="#brief">01 The brief</a><a href="#exception">02 The exception</a><a href="#outcomes">03 The decision</a><a href="#record">04 The record</a><a href="#evidence-boundary">05 What is shared</a></nav>
    <section className="foundation-content story-introduction" id="full-story"><aside className="notice"><strong>An illustrative example, not a live customer result.</strong><p>This simple scenario shows the intended trust layer. Receipt tooling exists in alpha; the complete workflow is not being presented as an available product.</p></aside><div className="scenario-brief"><div><p className="eyebrow">The example</p><h2>Assess the supplier.<br/>Keep the decision human.</h2><p>The agent does the groundwork. The application holds the limit. A person makes the consequential call. The record keeps the story together.</p></div><dl><div><dt>Agent’s responsibility</dt><dd>Gather evidence and prepare the recommendation.</dd></div><div><dt>Person’s responsibility</dt><dd>Decide whether the evidence supports acceptance.</dd></div><div><dt>Application’s responsibility</dt><dd>Enforce the scope and hold actions that need approval.</dd></div></dl></div></section>
    <section className="foundation-content story-chapters" aria-label="The assessment workflow">{chapters.map((chapter,index) => <article className="story-chapter" id={chapter.id} key={chapter.id}><div className="story-chapter-copy"><p className="eyebrow">0{index+1} / {chapter.role}</p><h2>{chapter.title}</h2><p>{chapter.copy}</p></div><aside className="story-evidence"><p className="eyebrow">Illustrative work record</p><h3>{chapter.record}</h3><ul>{chapter.items.map(item => <li key={item}>{item}</li>)}</ul></aside></article>)}</section>
    <section className="outcome-section" id="outcomes"><div className="outcome-heading"><p className="eyebrow">One job. More than one honest ending.</p><h2>The record should keep the “no”<br/>as carefully as the “yes”.</h2><p>These are alternative paths through the same proposed workflow. None is a live action or a universal verification result.</p></div><div className="outcome-grid">
      <article id="accepted"><span className="outcome-tag">Path A / Accepted</span><h3>Better evidence.<br/>A new decision.</h3><p>An updated certificate is received and assessed. The reviewer accepts the recommendation against that version. The original exception remains in the history.</p><dl><dt>Recorded outcome</dt><dd>Recommendation accepted</dd><dt>Not implied</dt><dd>Supplier guaranteed safe, or an order placed</dd></dl></article>
      <article id="more-evidence"><span className="outcome-tag">Path B / More evidence</span><h3>The answer is<br/>“not yet”.</h3><p>The reviewer requests a current certificate. The job remains unresolved until the new material is assessed. If the review deadline expires, the application keeps acceptance on hold.</p><dl><dt>Recorded outcome</dt><dd>Further evidence requested</dd><dt>Not implied</dt><dd>Approval by silence or by elapsed time</dd></dl></article>
      <article id="rejected"><span className="outcome-tag">Path C / Rejected</span><h3>A clear reason<br/>not to proceed.</h3><p>The evidence does not meet the organisation’s criteria. The reviewer rejects the recommendation and records why. Any later reassessment is a new, linked decision.</p><dl><dt>Recorded outcome</dt><dd>Recommendation rejected</dd><dt>Not implied</dt><dd>Erasing the work or rewriting the earlier decision</dd></dl></article>
    </div></section>
    <section className="foundation-content" id="changed-evidence"><div className="scenario-brief"><div><p className="eyebrow">The evidence changes</p><h2>Changed is not the same as corrected.</h2><p>A legitimate update and a mismatched disclosure need different handling. Neither should quietly inherit the old decision.</p></div><div className="evidence-cases"><article><h3>A new version arrives.</h3><p>Retain the old record. Create a new evidence commitment and link the reassessment to the earlier work. The reviewer makes a fresh decision against the new version.</p></article><article><h3>The disclosed file does not match.</h3><p>The integrity check fails. Obtain the original version or record a new one explicitly. Do not display the earlier approval as applying to the changed file.</p></article><article><h3>The evidence cannot be retrieved.</h3><p>Report that the evidence is unavailable. The anchor may still exist, but it cannot recreate the file or turn an incomplete check into success.</p></article></div></div></section>
    <section className="foundation-band" id="record"><div><p className="eyebrow">After the decision</p><h2>A decision with a history.<br/>Not just a green tick.</h2><p>The proposed review package links the brief, evidence and decision so an authorised recipient can inspect the story later.</p><a className="button primary" href="/developers">Meet the receipt tooling →</a></div><div className="decision-record"><p className="eyebrow">Illustrative package / accepted path</p><dl><div><dt>Work</dt><dd>Supplier recommendation</dd></div><div><dt>Earlier exception</dt><dd>Certificate expired</dd></div><div><dt>Reviewed material</dt><dd>Updated certificate · version 2</dd></div><div><dt>Human decision</dt><dd>Accept recommendation</dd></div><div><dt>Purchase authority</dt><dd>Not granted by this review</dd></div><div><dt>Anchor and signature checks</dt><dd>Not executed in this illustration</dd></div></dl><p>This human-readable package is a product concept, not a literal receipt schema.</p></div></section>
    <EvidenceBoundary/>
    <section className="foundation-band"><div><p className="eyebrow">Why the record matters</p><h2>Less reconstruction.<br/>A clearer hand-off.</h2></div><div><p>The intended benefit is a decision history another team can inspect without rebuilding the job from scattered logs. Pilot work still needs to establish the time saved and the value to buyers.</p><p>Matching evidence does not establish its truth. A recorded approval does not make judgement infallible. The useful question is always: what was checked, by whom, and against which version?</p><a className="button primary" href="/product">See how the product fits →</a></div></section>
    <section className="foundation-content narrow"><p className="eyebrow">Beyond this workflow</p><h2>Start with agents.<br/>Build toward a wider world.</h2><p>The same need for accountable history reaches into cross-organisation services and physical machines. Each new setting needs its own evidence and assurance.</p><div className="actions"><a className="button primary" href="/vision">Explore the vision →</a><a className="arrow-link" href="/status">What exists today</a></div></section><Footer/>
  </main>;
}
