import { Footer, PageHeader } from "../components";

const offers = [
  { name: "Design partner pilot", price: "£15k–£30k fixed", timing: "Indicative · 8–12 weeks", summary: "Take one important AI workflow from vague concern to a usable trust design.", details: ["Workflow and decision mapping", "Authority, exception and review model", "A measured prototype and evidence plan"] },
  { name: "Trust workspace", price: "£2k–£5k / month", timing: "Indicative · planned post-testnet", summary: "A shared place for authorised teams to review the story behind consequential AI work.", details: ["Case and record review", "Policy and authority templates", "Exportable evidence for internal review"] },
  { name: "Independent record API", price: "£0.05–£0.25 / recorded event", timing: "Illustrative · usage bands to be tested", summary: "Developer tools for connecting actions, evidence and selected checks to an independent record.", details: ["SDK and API access", "Batching and proof lookup", "Clear separation of platform and network costs"] },
];

export const metadata = { title: "Products | Orvessian", description: "Indicative product planning for Orvessian trust infrastructure.", openGraph: { images: [] }, twitter: { images: [] } };

export default function Products() {
  return <main><PageHeader label="Products / indicative planning" title="Trust products for AI that acts."><p>Orvessian is being designed for organisations that need AI to move forward without losing sight of what happened. These are planning ranges—not a current offer—and will be reviewed against testnet evidence.</p></PageHeader>
    <section className="commercial-intro"><div><p className="eyebrow">A simple commercial model</p><h2>Pay for the trust work.<br /><em>See the network cost.</em></h2></div><div><p>We expect the business to combine implementation support, a shared review workspace and usage-based developer tooling. If a future network fee applies, it should be visible—not hidden inside a black box.</p><p>That means customers pay for useful software and support, not a token story.</p></div></section>
    <section className="product-offers" aria-labelledby="offers-heading"><div className="offer-heading"><p className="eyebrow">The planned offers</p><h2 id="offers-heading">Start with the work that matters.</h2><p>Each offer is designed around a different point of entry. Availability, scope and price will be confirmed only after the relevant testnet gates are met.</p></div><div className="offer-grid">{offers.map((offer, index) => <article key={offer.name}><p className="offer-number">0{index + 1}</p><h3>{offer.name}</h3><p className="offer-price">{offer.price}</p><p className="offer-timing">{offer.timing}</p><p className="offer-summary">{offer.summary}</p><ul>{offer.details.map(detail => <li key={detail}>{detail}</li>)}</ul></article>)}</div></section>
    <section className="commercial-boundary"><div><p className="eyebrow">What this is—and is not</p><h2>Commercial clarity before commercial access.</h2></div><div className="commercial-boundary-list"><article><h3>Included in the model</h3><p>Integration and design work, software access, support, and measured usage of the record and review layer.</p></article><article><h3>Kept separate</h3><p>Any future network gas or anchoring cost should be shown clearly. It is not a margin disguised as a product fee.</p></article><article><h3>Not being offered today</h3><p>No public sale. No token pricing. No current production offer.</p></article></div></section>
    <section className="pricing-gates"><div><p className="eyebrow">Before testnet</p><h2>What we still need to prove.</h2><p>Indicative prices are a starting hypothesis. They need to work for customers and for the system behind them.</p></div><ol><li><span>01</span><div><h3>Real cost per record</h3><p>Measure batching, durable evidence, indexing and support—not just a single transaction.</p></div></li><li><span>02</span><div><h3>Useful service levels</h3><p>Set honest limits for confirmation, recovery and review based on multi-host testnet evidence.</p></div></li><li><span>03</span><div><h3>Customer value</h3><p>Validate that the record reduces review effort and makes exceptions easier to explain.</p></div></li><li><span>04</span><div><h3>Open network policy</h3><p>Decide sustainable fees, anti-spam controls and public access only after the protocol evidence is ready.</p></div></li></ol></section>
    <section className="products-next"><p className="eyebrow">The underlying product</p><h2>A product layer around an independent record.</h2><p>The commercial offers sit above the trust layer. They do not replace an organisation’s agent runtime, real-time controls or human judgement.</p><a className="arrow-link" href="/product">Understand the trust layer <span>→</span></a></section><Footer />
  </main>;
}
