import { Footer, PageHeader, repository } from "../components";

export const metadata = { title: "Developers | Orvessian", description: "Local reference tooling for 0.4.0-alpha verification receipts and their explicit boundaries.", openGraph: { images: [] }, twitter: { images: [] } };

const flow = [
  ["01", "Commit the bytes", "Create a commitment over exact evidence bytes. Keep the returned random salt, source material and access policy in your own private evidence store."],
  ["02", "Create the receipt", "Pin the profile and its definition digest. Bind issuer, subject, event, evidence descriptors, chain destination and optional stream history."],
  ["03", "Sign and retain", "Prepare the EIP-191 attestation message, collect the signature and retain the original receipt, evidence openings and any later batch manifest."],
  ["04", "Anchor deliberately", "Use an individual anchor or a retained batch manifest. Anchoring is a separate action from evidence creation and application enforcement."],
  ["05", "Verify by dimension", "Check profile, opening, signature, authority, proof and canonical inclusion independently. Return the check you actually performed."],
];

export default function Developers() {
  return <main><PageHeader label="Developers / local alpha" title="Build a receipt. Inspect every boundary."><p>The current tooling is a local reference implementation. Begin with synthetic evidence, no live network connection and no claim that an anchor alone proves the outcome.</p></PageHeader>
    <section className="developer-start" id="content"><div><span className="stage-label">General format · 0.4.0-alpha</span><h2>Your first receipt is deliberately <em>local.</em></h2><p>From a checkout of the source repository, install dependencies and run the maintained example. It writes a synthetic machine-event receipt, an issuer-signed presentation and private evidence openings to the ignored build directory. It does not broadcast a transaction.</p></div><div className="code-card"><p>FROM THE REPOSITORY ROOT</p><pre><code>{`npm ci\nnode examples/verification-receipt.js\nnode sdk/typescript/verification-receipt-cli.js derive build/receipt-example/receipt.json`}</code></pre><p className="code-note">The Python reference CLI derives the same receipt format. TypeScript includes signature recovery and anchor helpers; Python does not yet provide signature recovery or an RPC client.</p></div></section>
    <section className="developer-flow"><div className="paper-section-head"><p className="eyebrow">The implementation path</p><h2>Five steps. No hidden trust leap.</h2></div><div>{flow.map(([number,title,copy]) => <article key={number}><span>{number}</span><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></section>
    <section className="developer-contract"><div><p className="eyebrow">The envelope</p><h2>Version, profile, context, event, commitments and links.</h2><p>The 0.4.0-alpha receipt schema accepts only documented envelope fields. Application-specific meaning belongs in exact-byte evidence and versioned profiles, so it cannot silently disappear from the commitment.</p></div><dl><div><dt>Profile</dt><dd>URI, semantic version and definition digest</dd></div><div><dt>Context</dt><dd>Decimal chain ID and lowercase anchor contract</dd></div><div><dt>Event</dt><dd>Namespaced type, persisted identifier and claimed time</dd></div><div><dt>Commitments</dt><dd>One to thirty-two typed evidence descriptors</dd></div><div><dt>Stream</dt><dd>Optional session, sequence and predecessor link</dd></div><div><dt>Links</dt><dd>Optional parents, corrections and related records</dd></div></dl></section>
    <section className="developer-boundaries"><div><p className="eyebrow">Useful failures</p><h2>Design the verifier to say what it <em>doesn’t know.</em></h2></div><div className="boundary-list"><article><h3>Missing evidence</h3><p>An anchor can remain available after source material is lost. It cannot recreate the file or complete a missing opening.</p></article><article><h3>Unsupported assurance</h3><p>A general receipt may bind evidence but does not inherit historical authority or ZK policy-proof semantics from the authorised AVR flow.</p></article><article><h3>Changed material</h3><p>A different file fails an integrity comparison. Treat a legitimate update as a new linked record and fresh decision.</p></article></div></section>
    <section className="foundation-content safety-product"><p className="eyebrow">Planned safety profile</p><h2>Record a control event without making the record the control.</h2><p>The next profile is designed for integrations that already have a policy gateway, sandbox or monitor. It will bind selected policy versions, tool requests, alerts and authorised interventions to a reviewable timeline.</p><div className="notice"><strong>Current availability</strong><p>The safety evidence profile and gateway example are planned testnet work. The local alpha does not yet ship this profile, a real-time policy gateway or a safety verdict.</p></div><a className="arrow-link" href="/safety">Read the intended scope and boundaries <span>→</span></a></section>
    <section className="developer-links"><h2>Read, run, then challenge the boundary.</h2><a href={`${repository}/blob/main/docs/verification-receipt-developer-guide.md`}>Developer guide <span>Complete local flow →</span></a><a href={`${repository}/tree/main/spec/verification-receipt`}>Profiles and schema <span>Exact format material →</span></a><a href={`${repository}/blob/main/docs/verification-receipt-readiness-review.md`}>Readiness review <span>Release gates →</span></a></section><Footer/></main>;
}
