import { Footer, PageHeader, repository } from "../components";

export const metadata = { title: "Project status | Orvessian", description: "Current alpha capabilities, evidence and release gates.", openGraph: { images: [] }, twitter: { images: [] } };

export default function Status() {
  return <main><PageHeader label="Project status / source snapshot · 19 September 2026" title="Progress with the limits attached."><p>This is a dated development-status summary, not a live network monitor. It separates implemented work, bounded demonstrations and release work still ahead.</p></PageHeader>
    <section className="foundation-content"><div className="foundation-grid"><article><span className="stage-label">Implemented local alpha</span><h2>Receipt tooling</h2><p>General 0.4.0-alpha receipts, typed profiles, signed presentations, private evidence openings and TypeScript/Python reference examples are in the current source.</p></article><article><span className="stage-label">Integrated internal alpha</span><h2>Bounded evidence</h2><p>Synthetic actions exercised authority, a narrowly scoped policy proof, anchoring, batching, recovery and lookup on a development chain. This is integration evidence, not production assurance.</p></article><article><span className="stage-label">Foundation active</span><h2>Closed testnet</h2><p>The closed-testnet foundation defines a private operating model and acceptance gates. It does not launch a testnet, open public RPC or settle final network parameters.</p></article></div>
      <div className="status-update"><span>Latest repository evidence / 18 September</span><h2>GPU-miner development profile rechecked.</h2><p>On a fresh RTX 3060 loopback profile, ten GPU-mined KawPoW blocks were independently accepted by a separate CPU validator. That is useful interoperability evidence only: no public-network, production-capacity, final-consensus or economics claim follows from it.</p></div>
      <div className="status-update"><span>Next product increment / planned testnet work</span><h2>Agent safety evidence profile and gateway example.</h2><p>The proposed profile will cover selected policy bindings, monitor alerts and authorised interventions. It is not implemented safety monitoring, a live containment service or proof that an agent was safe.</p></div>
      <div className="reading-list"><h2>Inspect the source material.</h2><a href={repository + "/blob/main/docs/verification-receipt-readiness-review.md"}>Receipt readiness review <span>Scope and limitations →</span></a><a href={repository + "/blob/main/docs/phase-3-integrated-alpha.md"}>Integrated alpha <span>Reproduction and boundaries →</span></a><a href={repository + "/blob/main/docs/phase-4-closed-testnet-foundation.md"}>Closed-testnet foundation <span>Planning, not a launch →</span></a><a href={repository + "/blob/main/docs/phase-2a-g3-network-validation.md"}>G3 network validation <span>Development measurement →</span></a></div><aside className="notice"><strong>What is not being claimed</strong><p>No production network, audited stable protocol, proven customer adoption, universal AI correctness or live-robot safety assurance. Independent developer trials, durable evidence operations, typed verifier outcomes, stable SDK packaging and live general-format integration remain release gates.</p></aside></section><Footer /></main>;
}
