'use client';
import {useEffect,useState} from 'react';
type Agent={agentRef:string;environment:string;deploymentRef:string;ownerRef:string;purpose:string;modelRef:string;configVersion:string;heartbeatStatus:string;lastHeartbeatAt:string|null;lastEventReceivedAt:string|null};
type Registry={agents:Agent[];nextOffset:number|null;asOf:string;coverage:string};
export default function AgentsPanel({workspace,revision}:{workspace:string;revision:number}){
 const [data,setData]=useState<Registry|null>(null),[error,setError]=useState(''),[offset,setOffset]=useState(0);
 useEffect(()=>setOffset(0),[workspace]);
 useEffect(()=>{const controller=new AbortController();setData(null);setError('');fetch('/api/workspace?'+new URLSearchParams({action:'agents',workspace,limit:'50',offset:String(offset)}),{signal:controller.signal,cache:'no-store'}).then(async response=>{const body=await response.json();if(!response.ok)throw Error(response.status===404?'Agent registry is not available on this API deployment yet.':body.error||'Registry unavailable');return body;}).then(body=>{if(!controller.signal.aborted)setData(body);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[workspace,revision,offset]);
 return <section className="gp-panel"><h2>Agent directory</h2><p>Registered deployments, their owners and reporting signals. Register through the scoped ingestion API or Python client.</p>{error?<p role="alert">{error}</p>:!data?<p role="status">Loading agent directory…</p>:<><p>{data.coverage}</p><p>Snapshot {data.asOf}</p>{!data.agents.length?<p>No registered deployments. Existing activity is not automatically enrolled in the registry.</p>:<div className="gp-table-wrap"><table><thead><tr><th>Agent / purpose</th><th>Owner</th><th>Environment / deployment</th><th>Model / configuration</th><th>Heartbeat</th><th>Last event received</th></tr></thead><tbody>{data.agents.map(a=><tr key={JSON.stringify([a.agentRef,a.environment,a.deploymentRef])}><td>{a.agentRef}<small>{a.purpose}</small></td><td>{a.ownerRef}</td><td>{a.environment}<small>{a.deploymentRef}</small></td><td>{a.modelRef}<small>{a.configVersion}</small></td><td>{a.heartbeatStatus}<small>{a.lastHeartbeatAt||'No heartbeat received'}</small></td><td>{a.lastEventReceivedAt||'No matching activity received'}</td></tr>)}</tbody></table></div>}<button disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-50))}>Previous agents</button> <button disabled={data.nextOffset===null} onClick={()=>setOffset(data.nextOffset!)}>Next agents</button></>}</section>;
}
