'use client';
import {useEffect,useRef,useState} from 'react';
type Rule={id:string;version:number;environment:string;condition:string;severity:string;thresholdMs?:number;activatedAt:string};
type Incident={id:string;event_id:string;rule_id:string;rule_version:number;severity:string;state:string;revision:number;detected_at:number};
type History={actionId:string;actorRef:string;action:string;reasonCode:string;revision:number;createdAt:number};
type Data={rules?:Rule[];incidents?:Incident[];destinations?:string[];scope?:string;total?:number;nextOffset?:number|null};
export default function GovernancePanel({workspace,revision,mode,canManage,onEvidence}:{workspace:string;revision:number;mode:'rules'|'incidents';canManage:boolean;onEvidence:(id:string)=>void}){
 const [data,setData]=useState<Data|null>(null),[detail,setDetail]=useState<{incident:Incident;history:History[]}|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0),[condition,setCondition]=useState('run-failed'),[preview,setPreview]=useState<{eventId:string;assessment:string}[]|null>(null);
 const retry=useRef<{signature:string;id:string}|null>(null);
 const [offset,setOffset]=useState(0);
 async function request(action:string,body?:unknown,id='',signal?:AbortSignal){
  const response=await fetch('/api/workspace?'+new URLSearchParams({action,workspace,id,limit:'50',offset:String(offset)}),{method:body?'POST':'GET',cache:'no-store',signal,headers:body?{'content-type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});
  const result=await response.json();if(!response.ok)throw Error(result.error||'Governance operation unavailable');return result;
 }
 useEffect(()=>{
  const controller=new AbortController();setData(null);setDetail(null);setError('');setPreview(null);
  request(mode==='rules'?'rules':'incidents',undefined,'',controller.signal).then(result=>{if(!controller.signal.aborted)setData(result);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});
  return()=>controller.abort();
 },[workspace,revision,mode,refresh,offset]);
 async function ruleAction(e:React.FormEvent<HTMLFormElement>,action:'rule'|'rule-preview'){
  e.preventDefault();setBusy(true);setError('');setNotice('');setPreview(null);const fields=new FormData(e.currentTarget);
  const rule:Record<string,unknown>={id:fields.get('id'),version:Number(fields.get('version')),environment:fields.get('environment'),condition,severity:fields.get('severity')};
  for(const key of ['agentRef','taskClass','destinationRef'])if(fields.get(key))rule[key]=fields.get(key);
  if(condition==='latency-exceeded')rule.thresholdMs=Number(fields.get('thresholdMs'));
  try{
   if(action==='rule-preview'){const eventIds=String(fields.get('eventIds')||'').split(',').map(s=>s.trim()).filter(Boolean);if(!eventIds.length)throw Error('Enter accepted event references to preview.');setPreview((await request(action,{rule,eventIds})).results);}
   else{const result=await request(action,rule);setNotice(result.status==='duplicate'?'This exact rule version already exists.':'Rule version activated for subsequently received records.');setRefresh(v=>v+1);}
  }catch(e){setError((e as Error).message);}finally{setBusy(false);}
 }
 const detailController=useRef<AbortController|null>(null);
 useEffect(()=>()=>detailController.current?.abort(),[]);
 async function inspect(id:string){detailController.current?.abort();const controller=new AbortController();detailController.current=controller;setDetail(null);setError('');try{const result=await request('incident',undefined,id,controller.signal);if(!controller.signal.aborted)setDetail(result);}catch(e){if(!controller.signal.aborted)setError((e as Error).message);}}
 async function transition(e:React.FormEvent<HTMLFormElement>){
  e.preventDefault();if(!detail)return;setBusy(true);setError('');setNotice('');const fields=new FormData(e.currentTarget),action=String(fields.get('action')),reasonCode=String(fields.get('reasonCode'));
  const signature=JSON.stringify([detail.incident.id,detail.incident.revision,action,reasonCode]);if(retry.current?.signature!==signature)retry.current={signature,id:crypto.randomUUID()};
  try{await request('incident-action',{actionId:retry.current.id,action,reasonCode,expectedRevision:detail.incident.revision},detail.incident.id);retry.current=null;setNotice('Incident action recorded.');setRefresh(v=>v+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}
 }
 return <section className="gp-panel" aria-label={mode==='rules'?'Governance rules':'Detected incidents'}><h2>{mode==='rules'?'Governance rules':'Detected incidents'}</h2>
  <p>{mode==='rules'?'Versioned conditions applied to customer-submitted records. A breach creates an incident; it does not stop an agent.':'Operational incidents detected from submitted records. These states are separate from immutable alert records and their receipt status.'}</p>
  {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{!data&&!error&&<p role="status">Loading governance records…</p>}
  {data&&mode==='rules'&&<><div className="gp-table-wrap"><table><thead><tr><th>Rule / version</th><th>Environment</th><th>Condition</th><th>Severity</th><th>Activated (UTC)</th></tr></thead><tbody>{data.rules?.map(rule=><tr key={rule.id}><td>{rule.id} · v{rule.version}</td><td>{rule.environment}</td><td>{rule.condition}{rule.thresholdMs!==undefined?` > ${rule.thresholdMs} ms`:''}</td><td>{rule.severity}</td><td>{rule.activatedAt}</td></tr>)}</tbody></table></div>{!data.rules?.length&&<p>No rules have been configured.</p>}
   {canManage?<form onSubmit={e=>ruleAction(e,(e.nativeEvent as SubmitEvent).submitter?.getAttribute('value')==='preview'?'rule-preview':'rule')}><h3>Preview and activate a rule version</h3><p>Preview does not change history. Activation applies to records received after activation. Use a higher version when changing an existing rule.</p><fieldset disabled={busy}><div className="gp-toolbar"><label>Rule reference<input name="id" required pattern="[A-Za-z0-9._:-]+" maxLength={128}/></label><label>Version<input name="version" type="number" min={1} max={100000} defaultValue={1} required/></label><label>Environment<input name="environment" defaultValue="test" required pattern="[A-Za-z0-9._-]+" maxLength={64}/></label><label>Condition<select value={condition} onChange={e=>setCondition(e.target.value)}>{['run-failed','latency-exceeded','tool-permission-denied','tool-failed'].map(c=><option key={c}>{c}</option>)}</select></label>{condition==='latency-exceeded'&&<label>Latency threshold (ms)<input name="thresholdMs" type="number" min={0} max={86400000} required/></label>}<label>Severity<select name="severity" defaultValue="medium">{['info','low','medium','high','critical'].map(s=><option key={s}>{s}</option>)}</select></label><label>Agent reference (optional)<input name="agentRef" maxLength={128}/></label><label>Task class (optional)<input name="taskClass" maxLength={128}/></label><label>Notification destination<select name="destinationRef"><option value="">No notification</option>{data.destinations?.map(id=><option key={id}>{id}</option>)}</select></label></div><label>Accepted event references for preview (comma separated)<input name="eventIds" maxLength={2048}/></label><p><button type="submit" name="intent" value="preview">Preview selected records</button> <button className="gp-primary" type="submit" name="intent" value="activate">Activate rule version</button></p></fieldset></form>:<p>Read-only governance access. A governance administrator can preview and activate rule versions.</p>}
   {preview&&<section aria-label="Rule preview"><h3>Preview results</h3><p>Missing data is not a passing check. Preview covers only the selected accepted records.</p>{preview.map(result=><p key={result.eventId}>{result.eventId}: <strong>{result.assessment}</strong></p>)}</section>}
  </>}
  {data&&mode==='incidents'&&<><p>{data.scope} · {data.total} incidents</p>{!data.incidents?.length&&<p>No detected incidents are currently listed. This does not establish complete monitoring coverage.</p>}<div className="gp-table-wrap"><table><thead><tr><th>Rule / version</th><th>Severity</th><th>State</th><th>Detected (UTC)</th><th>Investigation</th></tr></thead><tbody>{data.incidents?.map(incident=><tr key={incident.id}><td>{incident.rule_id} · v{incident.rule_version}</td><td>{incident.severity}</td><td>{incident.state}</td><td>{new Date(incident.detected_at).toISOString()}</td><td><button disabled={busy} onClick={()=>inspect(incident.id)}>Open incident</button></td></tr>)}</tbody></table></div><button disabled={busy||offset===0} onClick={()=>setOffset(Math.max(0,offset-50))}>Previous incidents</button> <button disabled={busy||data.nextOffset==null} onClick={()=>setOffset(data.nextOffset!)}>Next incidents</button>
   {detail&&<section aria-label="Incident investigation"><h3>Incident investigation</h3><p>{detail.incident.id}</p><p>{detail.incident.state} · revision {detail.incident.revision} · {detail.incident.severity}</p><button onClick={()=>onEvidence(detail.incident.event_id)}>Inspect triggering record and evidence</button><h4>Action history</h4>{!detail.history.length&&<p>No incident actions recorded yet.</p>}{detail.history.map(item=><p key={item.actionId}>{item.action} · {item.reasonCode} · actor {item.actorRef} · {new Date(item.createdAt).toISOString()}</p>)}<p>Incident history is retained in the service journal; these actions are not yet signed or anchored.</p>{canManage&&<form onSubmit={transition}><fieldset disabled={busy}><label>Action<select name="action">{detail.incident.state==='open'&&<option value="acknowledge">Acknowledge</option>}{detail.incident.state!=='resolved'&&<option value="resolve">Resolve</option>}{detail.incident.state==='resolved'&&<option value="reopen">Reopen</option>}</select></label><label>Reason code<input name="reasonCode" required pattern="[A-Za-z0-9._:-]+" maxLength={128}/></label><button>Record incident action</button></fieldset></form>}</section>}
  </>}
 </section>;
}
