'use client';
import {useEffect,useState} from 'react';
import {readWorkspaceResponse} from '../../lib/workspace-response.js';
type Status={asOf:string;total:number;counts:{pending:number;batched:number;submitted:number;other:number};awaitingSubmission:number;oldestAwaitingAcceptedAt:string|null;oldestAwaitingAgeSeconds:number|null};
export default function PipelinePanel({workspace,revision}:{workspace:string;revision:number}){
 const [data,setData]=useState<Status|null>(null),[error,setError]=useState('');
 useEffect(()=>{const abort=new AbortController();setData(null);setError('');fetch('/api/workspace?'+new URLSearchParams({action:'evidence-status',workspace}),{cache:'no-store',signal:abort.signal}).then(response=>readWorkspaceResponse(response,{signal:abort.signal})).then(result=>{if(!abort.signal.aborted)setData(result);}).catch(error=>{if(!abort.signal.aborted)setError(error.message);});return()=>abort.abort();},[workspace,revision]);
 return <section className="gp-panel"><h2>Evidence delivery</h2><p>All accepted records in this project, across reporting periods. Submission status is separate from verification of a signed receipt or confirmation on Base.</p>{error?<p role="alert">Evidence delivery unavailable. Use Refresh to try again.</p>:!data?<p role="status">Loading evidence delivery…</p>:<><div className="gp-kpis">{[['Awaiting a batch',data.counts.pending],['Batched, awaiting submission',data.counts.batched],['Submission recorded',data.counts.submitted],['Other states',data.counts.other]].map(([label,count])=><article key={label}><p>{label}</p><strong>{count}</strong></article>)}</div><p>{data.total} accepted records · Snapshot {data.asOf}</p><p>{data.oldestAwaitingAcceptedAt?`Oldest record awaiting submission was accepted at ${data.oldestAwaitingAcceptedAt} (${data.oldestAwaitingAgeSeconds} seconds before this snapshot).`:'No pending or batched records at this snapshot.'}</p><p>Age runs from acceptance, not the last processing attempt. Inspect individual records for trusted signatures, batch membership and current Base confirmation. These observations do not prove worker liveness or a delivery SLA.</p></>}</section>;
}
