'use client';
import {useEffect,useRef,useState} from 'react';
import './reviews.css';
import ToolActivityPanel, {type ToolActivity} from './tool-activity';
type RecordEvent={eventId:string;eventType:string;occurredAt:string;receivedAt?:string;agentRef?:string;runRef?:string;caseRef?:string;environment:string;model?:{modelRef:string;deploymentRef:string;configVersion:string;providerRef:string};activity?:ToolActivity & {taskClass?:string;latencyMs?:number};result?:{predictedLabel?:string;decisionCode?:string;status?:string};source:{kind:string;keyRef:string;integrationVersion:string};outcome?:{label:string;labelSource:string;evaluatorRef:string;rubricVersion?:string};policy?:{version:string}};
type Investigation={event:RecordEvent;history:RecordEvent[];reviewState:string;canReview:boolean;asOf:string};
type Queue={rows:{event:RecordEvent;reviewState:string}[];counts:Record<string,number>;total:number;nextOffset:number|null;asOf:string};
const names:Record<string,string>={'awaiting-review':'Awaiting review',reviewed:'Reviewed','needs-investigation':'Needs investigation',conflicting:'Multiple outcomes','metadata-required':'Missing review metadata',all:'All decisions'};
export default function ReviewsPanel({workspace,from,to,revision,initialId,onEvidence}:{workspace:string;from:string;to:string;revision:number;initialId:string;onEvidence:(id:string)=>void}){
 const [queue,setQueue]=useState<Queue|null>(null),[detail,setDetail]=useState<Investigation|null>(null),[id,setId]=useState(initialId),[state,setState]=useState('awaiting-review'),[offset,setOffset]=useState(0),[search,setSearch]=useState(''),[error,setError]=useState(''),[detailError,setDetailError]=useState(''),[saved,setSaved]=useState(''),[saving,setSaving]=useState(false),[refresh,setRefresh]=useState(0);
 const [verdict,setVerdict]=useState('needs-investigation');
 const retry=useRef<{fingerprint:string;requestId:string}|null>(null),alive=useRef(true);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 useEffect(()=>setId(initialId),[initialId]);
 useEffect(()=>setVerdict('needs-investigation'),[id,refresh]);
 useEffect(()=>setOffset(0),[from,to,state,search]);
 async function read(action:string,signal:AbortSignal,extra:Record<string,string>={}){const response=await fetch('/api/workspace?'+new URLSearchParams({action,workspace,...extra}),{signal,cache:'no-store'});const body=await response.json();if(!response.ok)throw Error(body.error||'Workspace request failed');return body;}
 useEffect(()=>{if(!from||!to)return;const controller=new AbortController();setQueue(null);setError('');read('reviews',controller.signal,{from,to,state,q:search,limit:'25',offset:String(offset)}).then(data=>{if(!controller.signal.aborted)setQueue(data);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[workspace,from,to,state,search,offset,revision,refresh]);
 useEffect(()=>{const controller=new AbortController();setDetail(null);setDetailError('');if(id)read('investigation',controller.signal,{id}).then(data=>{if(!controller.signal.aborted)setDetail(data);}).catch(e=>{if(!controller.signal.aborted)setDetailError(e.message);});return()=>controller.abort();},[workspace,id,revision,refresh]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!detail||saving)return;const fields=new FormData(e.currentTarget);const payload={eventId:detail.event.eventId,verdict:String(fields.get('verdict')),label:String(fields.get('label')||''),rubricVersion:String(fields.get('rubricVersion'))};const fingerprint=JSON.stringify(payload);if(retry.current?.fingerprint!==fingerprint)retry.current={fingerprint,requestId:crypto.randomUUID()};setSaving(true);setSaved('');setDetailError('');try{const response=await fetch('/api/workspace?'+new URLSearchParams({action:'review',workspace}),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...payload,requestId:retry.current.requestId})});const body=await response.json();if(!response.ok)throw Error(body.error||'Review could not be saved');if(alive.current){setSaved('Review saved as a new immutable record. Its receipt may still be pending.');retry.current=null;setRefresh(v=>v+1);}}catch(e){if(alive.current)setDetailError((e as Error).message+' Retry unchanged fields to reuse the same request identity.');}finally{if(alive.current)setSaving(false);}}
 return <section className="gp-review-workspace" aria-label="Decision review workspace"><section className="gp-panel"><h2>Review queue</h2><p>Decision runs in the selected period, with linked outcomes available now. Reviews do not overwrite decisions.</p><div className="gp-toolbar"><label>Review status <select value={state} onChange={e=>setState(e.target.value)}>{Object.entries(names).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><form onSubmit={e=>{e.preventDefault();setSearch(String(new FormData(e.currentTarget).get('query')||''));}}><label>Agent, case or event <input name="query" maxLength={128}/></label> <button>Search</button></form></div>{error&&<p role="alert">{error}</p>}{queue?<><section className="gp-kpis">{Object.entries(queue.counts).map(([key,value])=><article key={key}><p>{names[key]}</p><strong>{value}</strong></article>)}</section><p>{queue.total} matching decisions · snapshot {queue.asOf}</p><div className="gp-table-wrap"><table><thead><tr><th>Decision / agent</th><th>Model / deployment</th><th>Recorded decision</th><th>Review state</th></tr></thead><tbody>{queue.rows.map(row=><tr key={row.event.eventId}><td><button className="gp-link" disabled={saving} onClick={()=>{setId(row.event.eventId);setSaved('');retry.current=null;}}>{row.event.agentRef||row.event.eventId}</button><small>{row.event.eventId}</small></td><td>{row.event.model?.modelRef}<small>{row.event.model?.deploymentRef}</small></td><td>{row.event.result?.predictedLabel||row.event.result?.decisionCode||'Not supplied'}</td><td>{names[row.reviewState]}</td></tr>)}</tbody></table></div>{!queue.rows.length&&<p>No decisions match these filters.</p>}<button disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-25))}>Previous decisions</button> <button disabled={queue.nextOffset===null} onClick={()=>setOffset(queue.nextOffset!)}>Next decisions</button></>:!error&&<p role="status">Loading review queue…</p>}</section>
 {saved&&<p role="status">{saved}</p>}{detailError&&<p role="alert">{detailError}</p>}{id&&!detail&&!detailError&&<p role="status">Loading decision…</p>}{detail&&<section className="gp-panel" aria-label="Decision investigation"><h2>Decision investigation</h2><dl><dt>Agent</dt><dd>{detail.event.agentRef}</dd><dt>Model / provider</dt><dd>{detail.event.model?.modelRef} / {detail.event.model?.providerRef}</dd><dt>Deployment / configuration</dt><dd>{detail.event.model?.deploymentRef} / {detail.event.model?.configVersion}</dd><dt>Environment / task</dt><dd>{detail.event.environment} / {detail.event.activity?.taskClass||'Not supplied'}</dd><dt>Case / run</dt><dd>{detail.event.caseRef||'No case reference'} / {detail.event.runRef}</dd><dt>Decision / execution status</dt><dd>{detail.event.result?.predictedLabel||detail.event.result?.decisionCode||'Not supplied'} / {detail.event.result?.status}</dd><dt>Occurred / received</dt><dd>{detail.event.occurredAt} / {detail.event.receivedAt}</dd><dt>Duration</dt><dd>{detail.event.activity?.latencyMs===undefined?'Not supplied':detail.event.activity.latencyMs+' ms'}</dd><dt>Review state</dt><dd>{names[detail.reviewState]}</dd></dl><button onClick={()=>onEvidence(detail.event.eventId)}>Verify decision receipt and Base status</button><ToolActivityPanel activity={detail.event.activity}/><h3>Linked review and outcome history</h3>{!detail.history.length&&<p>No linked reviews or outcomes yet.</p>}{detail.history.map(record=><article className="gp-review-history" key={record.eventId}><p><strong>{record.result?.decisionCode||record.outcome?.label||record.eventType}</strong> · {record.occurredAt}</p><p>Label: {record.outcome?.label||'No accuracy label'} · source: {record.source.integrationVersion==='portal-review-0.1.0'?'Authenticated portal review':record.outcome?.labelSource||'Submitted record'} · rubric: {record.outcome?.rubricVersion||record.policy?.version||'Not supplied'}</p><small>Reviewer/source reference: {record.source.keyRef}</small><p><button onClick={()=>onEvidence(record.eventId)}>Inspect review evidence</button></p></article>)}
 {detail.canReview?<form className="gp-review-form" key={detail.event.eventId} onSubmit={submit}><h3>Add a review</h3><p>Use a versioned rubric and bounded outcome code. Do not enter source text. Multiple outcome records are preserved and may suppress accuracy until resolved.</p><fieldset disabled={saving}><label>Assessment <select name="verdict" value={verdict} onChange={e=>setVerdict(e.target.value)}><option value="needs-investigation">Needs investigation</option><option value="correct" disabled={!detail.event.caseRef||!detail.event.result?.predictedLabel}>Correct</option><option value="incorrect" disabled={!detail.event.caseRef||!detail.event.result?.predictedLabel}>Incorrect</option></select></label> <label>Expected label (incorrect only) <input name="label" disabled={verdict!=='incorrect'} required={verdict==='incorrect'} maxLength={128} pattern="[A-Za-z0-9._:\-]+"/></label> <label>Rubric version <input name="rubricVersion" required maxLength={128} pattern="[A-Za-z0-9._:\-]+" placeholder="claims-review-v1"/></label><p><button className="gp-primary">{saving?'Saving review…':'Save new review'}</button></p></fieldset></form>:<p>Your workspace access is read-only. A workspace administrator must grant reviewer access to submit a review.</p>}<p>Reviewer identity is assigned from the session. An authenticated review is an assertion, not proof of accuracy or safety. Source content remains customer-held.</p></section>}</section>;
}
