'use client';
import {useEffect,useState,useRef} from 'react';
import AgentsPanel from './agents-panel';
import KeysPanel from './keys-panel';
import CustomerSettings from './customer-settings';
import AccountSessions from './account-sessions';
import PipelinePanel from './pipeline-panel';
import GovernancePanel from './governance-panel';
import ReviewsPanel from './reviews-panel';
import EvidencePanel, {type EvidenceDetail} from './evidence-panel';
type User={email:string;canCreateWorkspace?:boolean;workspaces:{id:string;name:string;workspaceId?:string;role?:string;canManageMembers?:boolean;canReview?:boolean;canManageGovernance?:boolean;canManageKeys?:boolean}[]};
type Report={alertSummary?:{total:number;returned:number;truncated:boolean};asOf:string;eventCount:number;kpis:Record<string,number>;models:{key:string;deployment:string;task:string;accuracy:number|null;accuracyStatus:string;correct:number;labelled:number;pending:number;p95LatencyMs:number|null}[];trends:{day:string;runs:number;failures:number}[];alerts:{eventId:string;signal:string;severity:string;disposition:string}[]};
type Event={eventId:string;eventType:string;occurredAt:string;agentRef?:string};
type PageData={events:Event[];total:number;nextOffset:number|null};
export default function Workspace(){
 const [user,setUser]=useState<User|null>(null),[ready,setReady]=useState(false),[workspace,setWorkspace]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('Overview'),[search,setSearch]=useState(''),[days,setDays]=useState('14'),[offset,setOffset]=useState(0),[revision,setRevision]=useState(0),[report,setReport]=useState<Report|null>(null),[events,setEvents]=useState<PageData|null>(null),[detail,setDetail]=useState<EvidenceDetail|null>(null);
 const [investigationId,setInvestigationId]=useState('');
 const [hostedSignIn,setHostedSignIn]=useState(false);
 const [reauthRequired,setReauthRequired]=useState(false);
 useEffect(()=>{const controller=new AbortController();fetch('/api/auth/status',{cache:'no-store',signal:controller.signal}).then(r=>r.json()).then(data=>{if(!controller.signal.aborted)setHostedSignIn(data.enabled===true);}).catch(()=>{});if(new URLSearchParams(window.location.search).get('reauthenticated')==='1'){setTab('Settings');history.replaceState(null,'','/workspace');}if(new URLSearchParams(window.location.search).get('signin')==='failed'){setError('Sign-in expired or could not be verified. Please start again.');history.replaceState(null,'','/workspace');}return()=>controller.abort();},[]);
 const detailController=useRef<AbortController|null>(null);
 function clear(){detailController.current?.abort();setReport(null);setEvents(null);setDetail(null);}
 async function api(query:string,init:RequestInit={}){const r=await fetch('/api/workspace?'+query,{...init,cache:'no-store'});const data=await r.json();if(init.signal?.aborted)throw new DOMException('Aborted','AbortError');if(r.status===401){setUser(null);clear();}if(r.status===403&&data.code==='reauthentication-required')setReauthRequired(true);if(!r.ok)throw new Error(data.error||'Request failed');return data;}
 useEffect(()=>{let active=true;api('action=session').then(u=>{if(active){setUser(u);setWorkspace(u.workspaces[0]?.id||'');if(u.canCreateWorkspace&&!u.workspaces.length)setTab('Settings');}}).catch(e=>{if(active&&e.message!=='Sign in required')setError(e.message);}).finally(()=>{if(active)setReady(true);});return()=>{active=false;};},[]);
 const [range,setRange]=useState({from:'',to:''});
 useEffect(()=>{const to=new Date(),from=new Date(to.getTime()-Number(days)*86400000);setRange({from:from.toISOString(),to:to.toISOString()});},[days,workspace,revision]);
 function query(action:string){return new URLSearchParams({action,workspace,...range,q:action==='events'?search:'',limit:'50',offset:String(offset)}).toString();}
 useEffect(()=>{clear();if(tab==='Agents'||tab==='Reviews'||tab==='Rules'||tab==='API keys'||tab==='Settings'){setBusy(false);setError('');return;}if(!user||!workspace||!range.from)return;const controller=new AbortController();setBusy(true);setError('');Promise.all([api(query('report'),{signal:controller.signal}),api(query('events'),{signal:controller.signal})]).then(([r,e])=>{if(!controller.signal.aborted){setReport(r);setEvents(e);}}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});return()=>controller.abort();},[user,workspace,range,offset,search,tab]);
 async function login(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=e.currentTarget,fields=new FormData(form);try{const u=await api('action=session',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:fields.get('email'),password:fields.get('password')})});form.reset();clear();setUser(u);setWorkspace(u.workspaces[0]?.id||'');if(u.canCreateWorkspace&&!u.workspaces.length)setTab('Settings');setRevision(v=>v+1);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function inspect(id:string){detailController.current?.abort();setDetail(null);const controller=new AbortController();detailController.current=controller;try{const value=await api(new URLSearchParams({action:'evidence',workspace,id}).toString(),{signal:controller.signal});if(!controller.signal.aborted)setDetail(value);}catch(e){if(!controller.signal.aborted)setError((e as Error).message);}}
 async function logout(){setBusy(true);try{const result=await api('action=session',{method:'DELETE'});if(result.logoutUrl){const url=new URL(result.logoutUrl);if(url.origin==='https://api.workos.com'&&url.pathname==='/user_management/sessions/logout'&&!url.username&&!url.password)window.location.assign(url.href);}setUser(null);clear();setWorkspace('');setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function refreshCustomer(projectId?:string){const u=await api('action=session');clear();setUser(u);setWorkspace(projectId&&u.workspaces.some((p:{id:string})=>p.id===projectId)?projectId:u.workspaces.some((p:{id:string})=>p.id===workspace)?workspace:u.workspaces[0]?.id||'');setRevision(v=>v+1);}
 if(!ready)return <main className="gp-panel"><p role="status">Checking your session…</p></main>;
 if(!user)return <main className="gp-shell" style={{justifyContent:'center',padding:'8vh 20px'}}><section className="gp-panel" style={{maxWidth:480,width:'100%',height:'fit-content'}}><a href="/">Orvessian</a><h1>Sign in to your workspace</h1>{hostedSignIn?<><p>Secure sign-in, registration and account recovery are handled by our identity provider.</p><a className="gp-primary" href="/api/auth/start?screen=sign-in">Sign in</a> <a href="/api/auth/start?screen=sign-up">Create an account</a></>:<><p>Use the account provisioned by your workspace administrator.</p><form onSubmit={login}><label>Email<input name="email" type="email" autoComplete="username" required maxLength={254} style={{display:'block',width:'100%',margin:'8px 0 20px',padding:12}}/></label><label>Password<input name="password" type="password" autoComplete="current-password" required maxLength={1024} style={{display:'block',width:'100%',margin:'8px 0 20px',padding:12}}/></label><button className="gp-primary" disabled={busy}>{busy?'Signing in…':'Sign in'}</button></form></>}{error&&<p role="alert">{error}</p>}<p>Your source conversations and documents stay in your systems.</p><a href="/portal">Explore the synthetic product demonstration →</a></section></main>;
 return <div className="gp-shell"><aside className="gp-sidebar"><a className="gp-brand" href="/">Orvessian</a><div className="gp-workspace gp-live-workspace"><small>WORKSPACE</small><label>Workspace<select aria-label="Workspace" value={workspace} onChange={e=>{clear();setInvestigationId('');setOffset(0);setWorkspace(e.target.value);}}>{user.workspaces.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><span>{user.email}</span></div><nav aria-label="Workspace sections">{['Overview','Agents','Decisions','Reviews','Models','Rules','Incidents','Reports',...(user.workspaces.find(w=>w.id===workspace)?.canManageKeys?['API keys']:[]),...(user.canCreateWorkspace?['Settings']:[])].map(t=><button key={t} aria-current={tab===t?'page':undefined} onClick={()=>{detailController.current?.abort();setTab(t);setDetail(null);}}>{t}</button>)}</nav><button onClick={logout} disabled={busy}>Sign out</button></aside><main className="gp-main"><div className="gp-demo-banner">Connected workspace · Customer-submitted records · {user.workspaces.find(w=>w.id===workspace)?.canManageGovernance?'Governance administrator':user.workspaces.find(w=>w.id===workspace)?.canReview?'Reviewer access':'Read-only access'}</div><header className="gp-header"><div><h1>{tab==='Overview'?'Your AI, in view.':tab}</h1><p>{user.workspaces.find(w=>w.id===workspace)?.name}</p></div><button className="gp-primary" onClick={()=>{if(user.canCreateWorkspace)void refreshCustomer().catch(e=>setError(e.message));else setRevision(v=>v+1);}} disabled={busy}>Refresh</button></header>{reauthRequired&&<section className="gp-panel" role="alert"><h2>Confirm your sign-in</h2><p>Sign in again to make this account or workspace change. You’ll return to Settings, where you can repeat your action.</p><a className="gp-primary" href="/api/auth/start?screen=sign-in&amp;reauth=1">Sign in again</a></section>}{tab!=='Agents'&&tab!=='API keys'&&tab!=='Settings'&&<div className="gp-toolbar"><label>Period <select value={days} onChange={e=>{clear();setOffset(0);setDays(e.target.value);}}><option value="7">Last 7 days</option><option value="14">Last 14 days</option><option value="30">Last 30 days</option><option value="365">Last year</option></select></label>{report&&<span>Snapshot {new Date(report.asOf).toLocaleString()} · UTC event times</span>}</div>}{error&&<p role="alert" className="gp-alert">{error}</p>}{busy&&<p role="status">Loading workspace records…</p>}{!workspace&&<p>{user.canCreateWorkspace?'Create a workspace or accept an invitation in Settings to get started.':'No workspaces have been assigned to this account.'}</p>}
 {tab==='Overview'&&workspace&&<PipelinePanel key={workspace} workspace={workspace} revision={revision}/>}
 {tab==='Settings'&&user.canCreateWorkspace&&<><AccountSessions key={user.email} onReauthenticationRequired={()=>setReauthRequired(true)}/><CustomerSettings key={user.email+'-'+(user.workspaces.find(w=>w.id===workspace)?.workspaceId||'new')} projects={user.workspaces} selected={workspace} revision={revision} onChanged={refreshCustomer} onReauthenticationRequired={()=>setReauthRequired(true)}/></>}
 {(tab==='Rules'||tab==='Incidents')&&workspace&&<GovernancePanel key={workspace+'-'+tab} workspace={workspace} revision={revision} mode={tab==='Rules'?'rules':'incidents'} canManage={!!user.workspaces.find(w=>w.id===workspace)?.canManageGovernance} onEvidence={inspect}/>} {tab==='Reviews'&&workspace&&<ReviewsPanel key={workspace} workspace={workspace} from={range.from} to={range.to} revision={revision} initialId={investigationId} onEvidence={inspect}/>}
 {tab==='API keys'&&workspace&&<KeysPanel key={workspace} workspace={workspace} tenantRef={user.workspaces.find(w=>w.id===workspace)?.workspaceId} revision={revision} canManage={!!user.workspaces.find(w=>w.id===workspace)?.canManageKeys} onReauthenticationRequired={()=>setReauthRequired(true)}/>}
 {tab==='Agents'&&workspace&&<AgentsPanel key={workspace} workspace={workspace} revision={revision}/>}
 {tab!=='Agents'&&tab!=='Reviews'&&tab!=='Rules'&&tab!=='API keys'&&tab!=='Settings'&&report&&<>{report.eventCount===0&&<section className="gp-panel"><h2>No records in this period</h2><p>Submit structured events using your project API credential, or select a wider period.</p></section>}{tab==='Overview'&&<><section className="gp-kpis">{[['agentsReporting','Agents reporting'],['runs','Model runs recorded'],['reviewedLabels','Adjudicated outcomes'],['openAlerts','Open incident records']].map(([key,label])=><article key={key}><p>{label}</p><strong>{report.kpis[key]||0}</strong></article>)}</section><section className="gp-panel"><h2>Activity over time</h2><p>Recorded runs and failures by day. Missing days are not evidence of inactivity or complete coverage.</p><div className="gp-table-wrap"><table><thead><tr><th>Day (UTC)</th><th>Runs</th><th>Failures</th></tr></thead><tbody>{report.trends.map(p=><tr key={p.day}><td>{p.day}</td><td><meter aria-label={`${p.day} runs`} value={p.runs} max={Math.max(1,...report.trends.map(t=>t.runs))}/> {p.runs}</td><td>{p.failures}</td></tr>)}</tbody></table></div></section></>}
 {(tab==='Overview'||tab==='Models')&&<section className="gp-panel"><h2>Model performance</h2><div className="gp-table-wrap"><table><thead><tr><th>Deployment / task</th><th>Adjudicated accuracy</th><th>Correct / labelled</th><th>Pending</th><th>p95 latency</th></tr></thead><tbody>{report.models.map(m=><tr key={m.key}><td>{m.deployment}<small>{m.task}</small></td><td>{m.accuracy===null?'Awaiting evidence':(m.accuracy*100).toFixed(1)+'%'}<small>{m.accuracyStatus}</small></td><td>{m.correct} / {m.labelled}</td><td>{m.pending}</td><td>{m.p95LatencyMs===null?'Unavailable':m.p95LatencyMs+' ms'}</td></tr>)}</tbody></table></div></section>}
 {tab==='Incidents'&&<section className="gp-panel"><h2>Submitted incident records</h2>{report.alertSummary?.truncated&&<p>Showing the latest {report.alertSummary.returned} of {report.alertSummary.total} incident records. Narrow the date range to inspect older records. KPI totals include all matching records.</p>}{!report.alerts.length&&<p>No submitted alerts in this period. Monitoring coverage is not established.</p>}{report.alerts.map(a=><article className="gp-incident" key={a.eventId}><h3>{a.signal}</h3><p>{a.severity} · {a.disposition}</p><button onClick={()=>inspect(a.eventId)}>Inspect record</button></article>)}</section>}
 {tab==='Reports'&&<section className="gp-panel"><h2>Governance report</h2><p>Export the current workspace and date window, including metric definitions, denominators and verification limitations.</p><a className="gp-primary" href={'/api/workspace?'+query('export')}>Download report · JSON</a></section>}
 <p className="gp-footnote">Open a record to inspect its signed receipt, batch proof and current Base status. Customer source signatures are not verified by this integration. Reporting agents are not a live inventory. Submitted alerts do not imply automatic monitoring or safety certification.</p></>}
 {tab==='Decisions'&&events&&<section className="gp-panel"><h2>Structured records</h2><form onSubmit={e=>{e.preventDefault();setOffset(0);setSearch(String(new FormData(e.currentTarget).get("search")||""));}}><label>Search by event, agent or case<input name="search" defaultValue={search} maxLength={256}/></label> <button>Search</button></form><p>{events.total} records in this period · newest first</p><div className="gp-table-wrap"><table><thead><tr><th>Time (UTC)</th><th>Record</th><th>Agent</th></tr></thead><tbody>{events.events.map(e=><tr key={e.eventId}><td>{e.occurredAt}</td><td><button className="gp-link" onClick={()=>inspect(e.eventId)}>{e.eventType}</button><small>{e.eventId}</small></td><td>{e.agentRef||'Not supplied'}</td></tr>)}</tbody></table></div><button disabled={busy||offset===0} onClick={()=>setOffset(Math.max(0,offset-50))}>Previous</button> <button disabled={busy||events.nextOffset===null} onClick={()=>setOffset(events.nextOffset!)}>Next</button></section>}
 {detail!==null&&<EvidencePanel onInvestigate={(id)=>{setInvestigationId(id);setDetail(null);setTab('Reviews');}} detail={detail} workspace={workspace} onClose={()=>{detailController.current?.abort();setDetail(null);}} onRefresh={()=>inspect(detail.event.eventId)}/>}</main></div>;
}
